export enum AccidentAssistanceTerminatedPeriodReasonPendencyEnum {
  LEAVE_DATE = 'LEAVE_DATE',
  COMPETENCE_BELOW_MINIMUM = 'COMPETENCE_BELOW_MINIMUM',
  INCONSISTENT_COMPETENCE = 'INCONSISTENT_COMPETENCE',
}
