export enum RetirementPermanentDisabilityRejectionDocumentTypeEnum {
  CNIS = 'CNIS',
  ADMINISTRATIVE_PROCEDURE_DENIAL = 'ADMINISTRATIVE_PROCEDURE_DENIAL',
  ADMINISTRATIVE_PROCEDURE_SUSPENSION = 'ADMINISTRATIVE_PROCEDURE_SUSPENSION',
  MEDICAL_SOCIAL_REPORT = 'MEDICAL_SOCIAL_REPORT',
}
