export enum PaymentPlanPaidResourceTypeEnum {
  LEGAL_PLEADING_COMPLETE_ANALYSIS = 'LEGAL_PLEADING_COMPLETE_ANALYSIS',
  LEGAL_PLEADING_SIMPLIFIED_ANALYSIS = 'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS',
  CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS = 'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS',
  CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS = 'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS',
}
