export enum PaymentPlanPaidResourceTypeEnum {
  LEGAL_PLEADING_COMPLETE_ANALYSIS = 'LEGAL_PLEADING_COMPLETE_ANALYSIS',
  LEGAL_PLEADING_SIMPLIFIED_ANALYSIS = 'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS',
  LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS = 'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS',
  RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS = 'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS',
  CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS = 'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS',
  CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS = 'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS',
  LEGAL_PROCEEDING_MONITORING = 'LEGAL_PROCEEDING_MONITORING',
  ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS = 'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS',
  ELOY_CHAT_LEGISLATION_QUESTIONS = 'ELOY_CHAT_LEGISLATION_QUESTIONS',
  ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH = 'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH',
}
