export enum TemporaryIncapacityBenefitTerminationReasonEnum {
  NAO_CARACTERIZACAO_DA_INCAPACIDADE_TEMPORARIA = 'NAO_CARACTERIZACAO_DA_INCAPACIDADE_TEMPORARIA',
  ALTA_PROGRAMADA_ANTECIPADA = 'ALTA_PROGRAMADA_ANTECIPADA',
  RECUPERACAO_DA_CAPACIDADE_LABORATIVA = 'RECUPERACAO_DA_CAPACIDADE_LABORATIVA',
  FALTA_DE_QUALIDADE_DE_SEGURADO_NA_DII = 'FALTA_DE_QUALIDADE_DE_SEGURADO_NA_DII',
  CARENCIA_INSUFICIENTE = 'CARENCIA_INSUFICIENTE',
  NAO_RECONHECIMENTO_DA_CONDICAO_DE_SEGURADO_ESPECIAL = 'NAO_RECONHECIMENTO_DA_CONDICAO_DE_SEGURADO_ESPECIAL',
  FALTA_DE_COMPROVACAO_DE_ATIVIDADE_RURAL_NO_PERIODO_DE_CARENCIA = 'FALTA_DE_COMPROVACAO_DE_ATIVIDADE_RURAL_NO_PERIODO_DE_CARENCIA',
  DOENCA_PREEXISTENTE_AO_INGRESSO_REINGRESSO_NO_RGPS = 'DOENCA_PREEXISTENTE_AO_INGRESSO_REINGRESSO_NO_RGPS',
  NAO_COMPARECIMENTO_A_PERICIA_AGENDADA = 'NAO_COMPARECIMENTO_A_PERICIA_AGENDADA',
  OUTRO = 'OUTRO',
}
