export enum DisabilityRetirementPlanningRejectionDenialReasonEnum {
  NAO_RECONHECIMENTO_CONDICAO_PCD = 'NAO_RECONHECIMENTO_CONDICAO_PCD',
  GRAU_DEFICIENCIA_INFERIOR = 'GRAU_DEFICIENCIA_INFERIOR',
  TEMPO_CONTRIBUICAO_INSUFICIENTE = 'TEMPO_CONTRIBUICAO_INSUFICIENTE',
  CARENCIA_NAO_ATINGIDA = 'CARENCIA_NAO_ATINGIDA',
  DOCUMENTACAO_MEDICA_INSUFICIENTE = 'DOCUMENTACAO_MEDICA_INSUFICIENTE',
  OUTRO = 'OUTRO',
}
