export enum DeathBenefitRejectionTimeAcceleratorTypeEnum {
  TEMPO_RURAL = 'TEMPO_RURAL',
  SERVICO_MILITAR = 'SERVICO_MILITAR',
  SERVICO_PUBLICO = 'SERVICO_PUBLICO',
  CTPS = 'CTPS',
  ALUNO_APRENDIZ = 'ALUNO_APRENDIZ',
  TRABALHO_NO_EXTERIOR = 'TRABALHO_NO_EXTERIOR',
  TRABALHO_INFORMAL = 'TRABALHO_INFORMAL',
  SENTENCA_TRABALHISTA = 'SENTENCA_TRABALHISTA',
}
