export enum LegalPleadingPetitionTypeEnum {
  ADMINISTRATIVE_REQUEST = 'requerimento_administrativo',
  COMPLIANCE_WITH_INSS_REQUIREMENT = 'cumprimento_de_exigencia_no_inss',
  ORDINARY_APPEAL_TO_CRPS = 'recurso_ordinario_ao_crps',
  INITIAL_COMPLAINT = 'peticao_inicial',
  WRIT_OF_MANDAMUS = 'mandado_de_seguranca',
  REPLY_TO_DEFENSE = 'impugnacao_a_contestacao_replica',
  CHALLENGE_TO_EXPERT_MEDICAL_REPORT = 'impugnacao_ao_laudo_medico_pericial',
  CHALLENGE_TO_JUDICIAL_SOCIOECONOMIC_REPORT = 'impugnacao_ao_laudo_socioeconomico_judicial',
  MOTION_FOR_CLARIFICATION = 'embargos_de_declaracao',
  ANSWER_TO_COMPLAINT = 'contestacao',
  UNNAMED_APPEAL_JEF = 'recurso_inominado_jef',
  APPEAL = 'apelacao',
  JURISPRUDENCE_UNIFORMIZATION_INCIDENT_TRU = 'incidente_de_uniformizacao_de_jurisprudencia_tru',
  JURISPRUDENCE_UNIFORMIZATION_INCIDENT_TNU = 'incidente_de_uniformizacao_de_jurisprudencia_tnu',
  OTHER = 'outros',
}
