export enum TemporaryDisabilityBenefitsTerminatedDocumentTypeEnum {
  ADMINISTRATIVE_PROCEDURE_DENIED = 'ADMINISTRATIVE_PROCEDURE_DENIED',
  CNIS = 'CNIS',
  CESSATION_OR_SUSPENSION_ADMINISTRATIVE_PROCEDURE = 'CESSATION_OR_SUSPENSION_ADMINISTRATIVE_PROCEDURE',
  CESSATION_OR_SUSPENSION_MEDICAL_SOCIAL_REPORT = 'CESSATION_OR_SUSPENSION_MEDICAL_SOCIAL_REPORT',
}
