import type { BaseEntityPropsInterface } from '@core/domain/schema/entity/base/base.entity.props.interface';
import type { AnalysisToolClientEntity } from '@module/customer/analysis-tool/domain/schema/entity/analysis-tool-client/analysis-tool-client.entity';
import type { AnalysisToolClientInterviewFormId } from '@module/customer/analysis-tool/domain/schema/entity/analysis-tool-client-interview-form/value-object/analysis-tool-client-interview-form-id/analysis-tool-client-interview-form-id.value-object';

export interface AnalysisToolClientInterviewFormEntityPropsInterface
  extends BaseEntityPropsInterface<AnalysisToolClientInterviewFormId> {
  analysisToolClient: AnalysisToolClientEntity;
  rg?: string | null;
  nit?: string | null;
  occupation?: string | null;
  neighborhood?: string | null;
  street?: string | null;
  addressNumber?: string | null;
  motherName?: string | null;
  fatherName?: string | null;
  spouseName?: string | null;
  ctpsNumber?: string | null;
  isMarried?: boolean | null;
  hasChildren?: boolean | null;
  childrenNames?: string[] | null;
  isRetired?: boolean | null;
  retirementType?: string | null;
  retirementBenefitNumber?: string | null;
  receivesSocialSecurityBenefit?: boolean | null;
  socialSecurityBenefitType?: string | null;
  socialSecurityBenefitNumber?: string | null;
  receivesWelfareBenefit?: boolean | null;
  welfareBenefitType?: string | null;
  welfareBenefitNumber?: string | null;
  hasInssDebt?: boolean | null;
  inssDebtAmount?: string | null;
  receivesBolsaFamilia?: boolean | null;
  workedInSpecialActivity?: boolean | null;
  specialActivityAgent?: string | null;
  hasPppOrLtcat?: boolean | null;
  pppLtcatCompany?: string | null;
  companyIsOpen?: boolean | null;
  workedWithElectricity?: boolean | null;
  workedAsSecurity?: boolean | null;
  exposedToExcessiveNoise?: boolean | null;
  workedInRuralArea?: boolean | null;
  familyLivedInRuralArea?: boolean | null;
  workedInPublicService?: boolean | null;
  heldPublicJob?: boolean | null;
  hiredByMunicipality?: boolean | null;
  hospitalizationDetails?: string | null;
  healthProblems?: string | null;
  accidentDetails?: string | null;
  workAccidentDetails?: string | null;
  medicalTreatment?: string | null;
  continuousMedication?: string | null;
  usesFarmaciaPopular?: boolean | null;
  medicalAttendanceType?: string | null;
  doctorName?: string | null;
  medicalLocation?: string | null;
  hasLaboratoryTests?: boolean | null;
  hasMedicalCertificates?: boolean | null;
  accidentSequelae?: string | null;
  pendingAdministrativeRequest?: string | null;
  ongoingJudicialProcess?: string | null;
  closedJudicialProcess?: string | null;
  previousBenefitRevision?: string | null;
  docIdAndResidence?: boolean | null;
  docPapAndJudicial?: boolean | null;
  docCnisExtract?: boolean | null;
  docPppLtcat?: boolean | null;
  docReservistCertificate?: boolean | null;
  docRuralDocuments?: boolean | null;
  docAllCtps?: boolean | null;
  docPublicAdminContracts?: boolean | null;
  docOthers?: string | null;
}
