export enum GeneralUrbanRetirementDenialPeriodPendencyReasonEnum {
  LEAVE_DATE = 'LEAVE_DATE',
  COMPETENCE_BELOW_MINIMUM = 'COMPETENCE_BELOW_MINIMUM',
  INCONSISTENT_COMPETENCE = 'INCONSISTENT_COMPETENCE',
  LATE_CONTRIBUTION = 'LATE_CONTRIBUTION',
}
