import type { MigrationInterface, QueryRunner } from 'typeorm';

export class TemporaryIncapacityBenefitRejectionFlow1776889475151 implements MigrationInterface {
  name = 'TemporaryIncapacityBenefitRejectionFlow1776889475151';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` ADD \`temporary_incapacity_benefit_rejection_id\` varchar(36) NULL`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temporary_incapacity_benefit_rejection_disability_analysis_cid\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`cid_ten_id\` varchar(50) NOT NULL, \`temporary_incapacity_benefit_rejection_disability_analysis_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temp_incapacity_benefit_rejection_disability_analysis_doc\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`file_name\` varchar(255) NOT NULL, \`type\` varchar(100) NOT NULL, \`temporary_incapacity_benefit_rejection_disability_analysis_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temporary_incapacity_benefit_rejection_disability_analysis\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`estimated_disability_start_date\` date NOT NULL, \`short_disability_description\` text NULL, \`disability_from_accident\` tinyint NOT NULL, \`disabling_condition_description\` text NULL, \`disability_from_severe_disease\` tinyint NOT NULL, \`severe_disease\` varchar(100) NULL, \`disease_custom_name\` varchar(255) NULL, \`disease_start_date\` date NULL, \`needs_constant_assistance_from_another_person\` tinyint NOT NULL, \`previous_disability_benefit\` tinyint NOT NULL, \`previous_benefit_number\` varchar(100) NULL, \`temporary_incapacity_benefit_rejection_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temporary_incapacity_benefit_rejection_document\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`file_name\` varchar(255) NOT NULL, \`type\` varchar(100) NOT NULL, \`temporary_incapacity_benefit_rejection_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temporary_incapacity_benefit_rejection_inss_benefit\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`inss_benefit\` varchar(255) NOT NULL, \`temporary_incapacity_benefit_rejection_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temp_incapacity_benefit_rejection_insured_status_document\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`file_name\` varchar(255) NOT NULL, \`type\` varchar(100) NOT NULL, \`temporary_incapacity_benefit_rejection_insured_status_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temporary_incapacity_benefit_rejection_insured_status\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`involuntary_unemployment\` tinyint NOT NULL, \`intention_to_prove_involuntary_unemployment\` tinyint NOT NULL, \`rural_insured_client\` tinyint NOT NULL, \`rural_period_start_date\` date NULL, \`rural_period_end_date\` date NULL, \`documents_description\` text NULL, \`temporary_incapacity_benefit_rejection_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temporary_incapacity_benefit_rejection_result\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`inss_decision_analysis\` longtext NULL, \`first_analysis\` longtext NULL, \`complete_analysis\` longtext NULL, \`complete_analysis_download\` longtext NULL, \`simplified_analysis\` longtext NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temp_incapacity_benefit_rejection_work_periods_earnings_history\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`competence\` date NULL, \`remuneration\` longtext NULL, \`indicators\` longtext NULL, \`payment_date\` date NULL, \`contribution\` longtext NULL, \`contribution_salary\` longtext NULL, \`competence_below_the_minimum\` tinyint NULL, \`temporary_incapacity_benefit_rejection_work_periods_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temporary_incapacity_benefit_rejection_work_periods\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`bond_origin\` varchar(255) NOT NULL, \`start_date\` date NOT NULL, \`end_date\` date NULL, \`category\` varchar(100) NOT NULL, \`competence_below_the_minimum\` tinyint NOT NULL, \`pendency_reason\` varchar(100) NULL, \`period_consideration\` varchar(50) NULL, \`contribution_average\` decimal(15,2) NULL, \`status\` tinyint NOT NULL, \`grace_period\` int NOT NULL, \`temporary_incapacity_benefit_rejection_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`temporary_incapacity_benefit_rejection\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`analysis_name\` varchar(255) NULL, \`request_entry_date\` date NULL, \`denial_date\` date NULL, \`requested_benefit_type\` varchar(255) NULL, \`category\` varchar(100) NULL, \`denial_reason\` varchar(255) NULL, \`denial_reason_description\` text NULL, \`condition\` varchar(100) NULL, \`condition_description\` text NULL, \`temporary_incapacity_benefit_rejection_result_id\` varchar(36) NULL, \`organization_member_id\` varchar(36) NULL, \`analysis_tool_client_id\` varchar(36) NULL, UNIQUE INDEX \`REL_18f678ea101ff58294df2071e0\` (\`temporary_incapacity_benefit_rejection_result_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `ALTER TABLE \`payment_plan_paid_resource\` CHANGE \`resource\` \`resource\` enum ('ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS',
    'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS',
    'ADMINISTRATIVE_REQUEST_GENERATOR_COMPLETE_ANALYSIS',
    'ADMINISTRATIVE_REQUEST_GENERATOR_SIMPLIFIED_ANALYSIS',
    'AUDIENCE_QUESTIONS_GENERATOR_COMPLETE_ANALYSIS',
    'AUDIENCE_QUESTIONS_GENERATOR_SIMPLIFIED_ANALYSIS',
    'BPC_ELDERLY_ANALYSIS_COMPLETE_ANALYSIS',
    'BPC_ELDERLY_ANALYSIS_SIMPLIFIED_ANALYSIS',
    'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS',
    'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS',
    'DEATH_BENEFIT_GRANT_COMPLETE_ANALYSIS',
    'DEATH_BENEFIT_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS',
    'DEATH_BENEFIT_GRANT_FIRST_ANALYSIS',
    'DEATH_BENEFIT_GRANT_INFORMAL_WORK_ANALYSIS',
    'DEATH_BENEFIT_GRANT_LABOR_COURT_DECISION_ANALYSIS',
    'DEATH_BENEFIT_GRANT_MILITARY_SERVICE_ANALYSIS',
    'DEATH_BENEFIT_GRANT_PUBLIC_SERVICE_ANALYSIS',
    'DEATH_BENEFIT_GRANT_RURAL_TIME_ANALYSIS',
    'DEATH_BENEFIT_GRANT_SIMPLIFIED_ANALYSIS',
    'DEATH_BENEFIT_GRANT_STUDENT_APPRENTICE_ANALYSIS',
    'DEATH_BENEFIT_GRANT_WORK_ABROAD_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_COMPLETE_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_CTPS_OUTSIDE_CNIS_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_FIRST_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_INFORMAL_WORK_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_INSS_DECISION_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_LABOR_COURT_DECISION_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_MILITARY_SERVICE_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_PUBLIC_SERVICE_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_RURAL_TIME_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_SIMPLIFIED_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_STUDENT_APPRENTICE_ANALYSIS',
    'DEATH_BENEFIT_REJECTION_WORK_ABROAD_ANALYSIS',
    'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS',
    'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_ADMINISTRATIVE_PROCESS_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_COMPLETE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_COMPLETE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_FIRST_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_INFORMAL_WORK_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_LABOR_COURT_DECISION_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_MILITARY_SERVICE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_PPP_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_PUBLIC_SERVICE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_RURAL_TIME_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_SIMPLIFIED_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_STUDENT_APPRENTICE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_GRANT_WORK_ABROAD_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_COMPLETE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_CTPS_OUTSIDE_CNIS_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_FIRST_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_INFORMAL_WORK_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_INSS_DECISION_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_LABOR_COURT_DECISION_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_MILITARY_SERVICE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_PPP_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_PUBLIC_SERVICE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_RURAL_TIME_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_SIMPLIFIED_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_STUDENT_APPRENTICE_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_REJECTION_WORK_ABROAD_ANALYSIS',
    'DISABILITY_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS',
    'ELOY_CHAT_ANALYSIS',
    'ELOY_CHAT_LEGISLATION_QUESTIONS',
    'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS',
    'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH',
    'FULL_OPINION_GENERATOR_COMPLETE_ANALYSIS',
    'FULL_OPINION_GENERATOR_SIMPLIFIED_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_ADMINISTRATIVE_REQUEST_DENIED_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_BENEFIT_AWARD_LETTER_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_COMPLETE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_COMPARE_CNIS_CTPS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_COMPLETE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_CTPS_OUTSIDE_CNIS_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_FIRST_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_INFORMAL_WORK_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_INSS_DECISION_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_LABOR_COURT_DECISION_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_MILITARY_SERVICE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_PPP_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_PUBLIC_SERVICE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_RURAL_TIME_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_SIMPLIFIED_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_STUDENT_APPRENTICE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_DENIAL_WORK_ABROAD_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_CNIS_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_COMPARE_CNIS_CTPS',
    'GENERAL_URBAN_RETIREMENT_GRANT_COMPLETE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_INFORMAL_WORK_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_LABOR_COURT_DECISION_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_MILITARY_SERVICE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_NO_END_DATE_DOCUMENTS_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_PUBLIC_SERVICE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_RURAL_TIME_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_SIMPLIFIED_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_SPECIAL_PERIOD_PPP_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_STUDENT_APPRENTICE_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_GRANT_WORK_ABROAD_ANALYSIS',
    'GENERAL_URBAN_RETIREMENT_SIMPLIFIED_ANALYSIS',
    'INITIAL_PETITION_GENERATOR_COMPLETE_ANALYSIS',
    'INITIAL_PETITION_GENERATOR_SIMPLIFIED_ANALYSIS',
    'INSURANCE_QUALITY_ANALYSIS_COMPLETE_ANALYSIS',
    'INSURANCE_QUALITY_ANALYSIS_SIMPLIFIED_ANALYSIS',
    'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS',
    'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS',
    'LEGAL_PLEADING_COMPLETE_ANALYSIS',
    'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS',
    'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS',
    'LEGAL_PROCEEDING_MONITORING',
    'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_COMPLETE_ANALYSIS',
    'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_SIMPLIFIED_ANALYSIS',
    'MEDICAL_QUESTION_GENERATOR_COMPLETE_ANALYSIS',
    'MEDICAL_QUESTION_GENERATOR_SIMPLIFIED_ANALYSIS',
    'MINI_ADVISOR_COMPLETE_ANALYSIS',
    'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS',
    'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS',
    'REGULATORY_UPDATES',
    'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS',
    'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS',
    'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS',
    'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS',
    'RURAL_TIMELINE_ANALYSIS_CONSOLIDATED_DOCUMENT_ANALYSIS',
    'RURAL_TIMELINE_ANALYSIS_INDIVIDUAL_PERIOD_DOCUMENT_ANALYSIS',
    'RURAL_TIMELINE_ANALYSIS_PERIOD_DOCUMENT_ANALYSIS',
    'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_ADJUSTMENT_SIMULATION',
    'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_IMPACT_ANALYSIS',
    'RURAL_TIMELINE_COMPLETE_ANALYSIS',
    'RURAL_TIMELINE_SIMPLIFIED_ANALYSIS',
    'SPECIAL_ACTIVITY_COMPLETE_ANALYSIS',
    'SPECIAL_ACTIVITY_SIMPLIFIED_ANALYSIS',
    'SPECIAL_CATEGORY_RETIREMENT_ADMINISTRATIVE_PROCEDURE_ANALYSIS',
    'SPECIAL_CATEGORY_RETIREMENT_CONVERSION_ANALYSIS',
    'SPECIAL_CATEGORY_RETIREMENT_RULES_ANALYSIS',
    'SPECIAL_CATEGORY_RETIREMENT_COMPLETE_ANALYSIS',
    'SPECIAL_CATEGORY_RETIREMENT_SIMPLIFIED_ANALYSIS',
    'SPECIAL_RETIREMENT_GRANT_COMPLETE_ANALYSIS',
    'SPECIAL_RETIREMENT_GRANT_FIRST_ANALYSIS',
    'SPECIAL_RETIREMENT_GRANT_SIMPLIFIED_ANALYSIS',
    'SPEECH_GENERATOR_COMPLETE_ANALYSIS',
    'SPEECH_GENERATOR_SIMPLIFIED_ANALYSIS',
    'SURVIVOR_PENSION_ANALYSIS_COMPLETE_ANALYSIS',
    'SURVIVOR_PENSION_ANALYSIS_COMPLETE_ANALYSIS_TEXT',
    'SURVIVOR_PENSION_ANALYSIS_DEPENDENT_PENSION_ANALYSES',
    'SURVIVOR_PENSION_ANALYSIS_RETIREMENT_RULES',
    'SURVIVOR_PENSION_ANALYSIS_SIMPLIFIED_ANALYSIS_TEXT',
    'TEACHER_ADMINISTRATIVE_PROCESS_ANALYSIS',
    'TEACHER_RETIREMENT_PLANNING_COMPLETE_ANALYSIS',
    'TEACHER_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS',
    'TEMPORARY_DISABILITY_BENEFITS_GRANT_COMPLETE_ANALYSIS',
    'TEMPORARY_DISABILITY_BENEFITS_GRANT_FIRST_ANALYSIS',
    'TEMPORARY_DISABILITY_BENEFITS_GRANT_SIMPLIFIED_ANALYSIS',
    'TEMPORARY_INCAPACITY_BENEFIT_REJECTION_INSS_DECISION_ANALYSIS',
    'TEMPORARY_INCAPACITY_BENEFIT_REJECTION_FIRST_ANALYSIS',
    'TEMPORARY_INCAPACITY_BENEFIT_REJECTION_COMPLETE_ANALYSIS',
    'TEMPORARY_INCAPACITY_BENEFIT_REJECTION_SIMPLIFIED_ANALYSIS') NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` CHANGE \`type\` \`type\` enum ('analise_rapida_cnis','planejamento_previdenciario_rgps','planejamento_aposentadoria_rpps','planejamento_previdenciario_professor','atividade_especial','analise_caso_judicial','analise_procedimento_administrativo_inss','gerador_perguntas_medicas','analise_geradora_objeção_laudo_medico_social','gerador_discurso','avaliacao_deficiencia_para_bpc','analise_renda_per_capita_para_bpc','analise_linha_tempo_rural','gerador_perguntas_audiencia','analise_qualidade_segurado','planejamento_aposentadoria_para_deficiente','concessao_aposentadoria_urbana_geral','analise_aposentadoria_urbana_geral','aposentadoria_categoria_especial','concessao_aposentadoria_especial','concessao_aposentadoria_para_deficiente','concessao_pensao_por_morte','indeferimento_pensao_por_morte','auxilio_incapacidade_temporaria','pensao_por_morte','indeferimento_aposentadoria_urbana_geral','indeferimento_aposentadoria_para_deficiente','bpc_ao_idoso', 'indeferimento_auxilio_incapacidade_temporaria') NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_disability_analysis_cid\` ADD CONSTRAINT \`FK_40e5be3953da2de601571052fee\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_disability_analysis_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_disability_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temp_incapacity_benefit_rejection_disability_analysis_doc\` ADD CONSTRAINT \`FK_6cb96d0a7cff7ff205192fcb51e\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_disability_analysis_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_disability_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_disability_analysis\` ADD CONSTRAINT \`FK_2edec45b0b1f35c03805bb92422\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_document\` ADD CONSTRAINT \`FK_7dca5138b462c51ae3f2a217e45\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_inss_benefit\` ADD CONSTRAINT \`FK_8188700956064af6338ecf974f9\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temp_incapacity_benefit_rejection_insured_status_document\` ADD CONSTRAINT \`FK_a9ae561fa235f8608f037e2743a\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_insured_status_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_insured_status\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_insured_status\` ADD CONSTRAINT \`FK_46765c3cd47977173693c4f3fa9\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temp_incapacity_benefit_rejection_work_periods_earnings_history\` ADD CONSTRAINT \`FK_8d024a755cdfc35f4af6239f2cc\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_work_periods_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_work_periods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_work_periods\` ADD CONSTRAINT \`FK_6013f9817945eb0e4b6c7c7878d\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection\` ADD CONSTRAINT \`FK_18f678ea101ff58294df2071e0c\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_result_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection\` ADD CONSTRAINT \`FK_133eeb984c158343c7a1f7c5bc5\` FOREIGN KEY (\`organization_member_id\`) REFERENCES \`organization_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection\` ADD CONSTRAINT \`FK_db1e64c3630f2023b1ead456bbe\` FOREIGN KEY (\`analysis_tool_client_id\`) REFERENCES \`analysis_tool_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_e2c6a1756f9f902c900f67cadae\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_e2c6a1756f9f902c900f67cadae\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection\` DROP FOREIGN KEY \`FK_db1e64c3630f2023b1ead456bbe\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection\` DROP FOREIGN KEY \`FK_133eeb984c158343c7a1f7c5bc5\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection\` DROP FOREIGN KEY \`FK_18f678ea101ff58294df2071e0c\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_work_periods\` DROP FOREIGN KEY \`FK_6013f9817945eb0e4b6c7c7878d\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temp_incapacity_benefit_rejection_work_periods_earnings_history\` DROP FOREIGN KEY \`FK_8d024a755cdfc35f4af6239f2cc\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_insured_status\` DROP FOREIGN KEY \`FK_46765c3cd47977173693c4f3fa9\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temp_incapacity_benefit_rejection_insured_status_document\` DROP FOREIGN KEY \`FK_a9ae561fa235f8608f037e2743a\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_inss_benefit\` DROP FOREIGN KEY \`FK_8188700956064af6338ecf974f9\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_document\` DROP FOREIGN KEY \`FK_7dca5138b462c51ae3f2a217e45\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_disability_analysis\` DROP FOREIGN KEY \`FK_2edec45b0b1f35c03805bb92422\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temp_incapacity_benefit_rejection_disability_analysis_doc\` DROP FOREIGN KEY \`FK_6cb96d0a7cff7ff205192fcb51e\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`temporary_incapacity_benefit_rejection_disability_analysis_cid\` DROP FOREIGN KEY \`FK_40e5be3953da2de601571052fee\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` CHANGE \`type\` \`type\` enum ('analise_rapida_cnis', 'planejamento_previdenciario_rgps', 'planejamento_aposentadoria_rpps', 'planejamento_previdenciario_professor', 'atividade_especial', 'analise_caso_judicial', 'analise_procedimento_administrativo_inss', 'gerador_perguntas_medicas', 'analise_geradora_objeção_laudo_medico_social', 'gerador_discurso', 'avaliacao_deficiencia_para_bpc', 'analise_renda_per_capita_para_bpc', 'analise_linha_tempo_rural', 'gerador_perguntas_audiencia', 'analise_qualidade_segurado', 'planejamento_aposentadoria_para_deficiente', 'concessao_aposentadoria_urbana_geral', 'analise_aposentadoria_urbana_geral', 'aposentadoria_categoria_especial', 'concessao_aposentadoria_especial', 'concessao_aposentadoria_para_deficiente', 'concessao_pensao_por_morte', 'indeferimento_pensao_por_morte', 'auxilio_incapacidade_temporaria', 'pensao_por_morte', 'indeferimento_aposentadoria_urbana_geral', 'indeferimento_aposentadoria_para_deficiente', 'bpc_ao_idoso') NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`payment_plan_paid_resource\` CHANGE \`resource\` \`resource\` enum ('LEGAL_PLEADING_COMPLETE_ANALYSIS', 'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS', 'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS', 'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS', 'TEACHER_RETIREMENT_PLANNING_COMPLETE_ANALYSIS', 'TEACHER_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS', 'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS', 'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS', 'LEGAL_PROCEEDING_MONITORING', 'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS', 'ELOY_CHAT_LEGISLATION_QUESTIONS', 'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH', 'ELOY_CHAT_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS', 'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS', 'SPECIAL_ACTIVITY_COMPLETE_ANALYSIS', 'SPECIAL_ACTIVITY_SIMPLIFIED_ANALYSIS', 'SPECIAL_RETIREMENT_GRANT_COMPLETE_ANALYSIS', 'SPECIAL_RETIREMENT_GRANT_SIMPLIFIED_ANALYSIS', 'SPECIAL_RETIREMENT_GRANT_FIRST_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS', 'MEDICAL_QUESTION_GENERATOR_SIMPLIFIED_ANALYSIS', 'MEDICAL_QUESTION_GENERATOR_COMPLETE_ANALYSIS', 'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_COMPLETE_ANALYSIS', 'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_SIMPLIFIED_ANALYSIS', 'SPEECH_GENERATOR_COMPLETE_ANALYSIS', 'SPEECH_GENERATOR_SIMPLIFIED_ANALYSIS', 'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS', 'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS', 'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS', 'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS', 'INSURANCE_QUALITY_ANALYSIS_COMPLETE_ANALYSIS', 'INSURANCE_QUALITY_ANALYSIS_SIMPLIFIED_ANALYSIS', 'INITIAL_PETITION_GENERATOR_COMPLETE_ANALYSIS', 'INITIAL_PETITION_GENERATOR_SIMPLIFIED_ANALYSIS', 'ADMINISTRATIVE_REQUEST_GENERATOR_COMPLETE_ANALYSIS', 'ADMINISTRATIVE_REQUEST_GENERATOR_SIMPLIFIED_ANALYSIS', 'FULL_OPINION_GENERATOR_COMPLETE_ANALYSIS', 'FULL_OPINION_GENERATOR_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_COMPLETE_ANALYSIS', 'RURAL_TIMELINE_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_INDIVIDUAL_PERIOD_DOCUMENT_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_PERIOD_DOCUMENT_ANALYSIS', 'AUDIENCE_QUESTIONS_GENERATOR_COMPLETE_ANALYSIS', 'AUDIENCE_QUESTIONS_GENERATOR_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_CONSOLIDATED_DOCUMENT_ANALYSIS', 'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_IMPACT_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_CNIS_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_COMPARE_CNIS_CTPS', 'GENERAL_URBAN_RETIREMENT_GRANT_SPECIAL_PERIOD_PPP_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_NO_END_DATE_DOCUMENTS_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_RURAL_TIME_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_MILITARY_SERVICE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_PUBLIC_SERVICE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_STUDENT_APPRENTICE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_WORK_ABROAD_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_INFORMAL_WORK_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_LABOR_COURT_DECISION_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_COMPLETE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_GRANT_SIMPLIFIED_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_COMPLETE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_SIMPLIFIED_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_ADMINISTRATIVE_REQUEST_DENIED_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_BENEFIT_AWARD_LETTER_ANALYSIS', 'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_ADJUSTMENT_SIMULATION', 'TEACHER_ADMINISTRATIVE_PROCESS_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_COMPLETE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_ADMINISTRATIVE_PROCESS_ANALYSIS', 'SPECIAL_CATEGORY_RETIREMENT_COMPLETE_ANALYSIS', 'SPECIAL_CATEGORY_RETIREMENT_SIMPLIFIED_ANALYSIS', 'SPECIAL_CATEGORY_RETIREMENT_CONVERSION_ANALYSIS', 'SPECIAL_CATEGORY_RETIREMENT_RULES_ANALYSIS', 'SPECIAL_CATEGORY_RETIREMENT_ADMINISTRATIVE_PROCEDURE_ANALYSIS', 'MINI_ADVISOR_COMPLETE_ANALYSIS', 'MINI_ADVISOR_SIMPLIFIED_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_COMPLETE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_SIMPLIFIED_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_FIRST_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_RURAL_TIME_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_MILITARY_SERVICE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_PUBLIC_SERVICE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_STUDENT_APPRENTICE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_WORK_ABROAD_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_INFORMAL_WORK_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_LABOR_COURT_DECISION_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_GRANT_PPP_ANALYSIS', 'DEATH_BENEFIT_GRANT_COMPLETE_ANALYSIS', 'DEATH_BENEFIT_GRANT_SIMPLIFIED_ANALYSIS', 'DEATH_BENEFIT_GRANT_FIRST_ANALYSIS', 'DEATH_BENEFIT_GRANT_RURAL_TIME_ANALYSIS', 'DEATH_BENEFIT_GRANT_MILITARY_SERVICE_ANALYSIS', 'DEATH_BENEFIT_GRANT_PUBLIC_SERVICE_ANALYSIS', 'DEATH_BENEFIT_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS', 'DEATH_BENEFIT_GRANT_STUDENT_APPRENTICE_ANALYSIS', 'DEATH_BENEFIT_GRANT_WORK_ABROAD_ANALYSIS', 'DEATH_BENEFIT_GRANT_INFORMAL_WORK_ANALYSIS', 'DEATH_BENEFIT_GRANT_LABOR_COURT_DECISION_ANALYSIS', 'DEATH_BENEFIT_REJECTION_COMPLETE_ANALYSIS', 'DEATH_BENEFIT_REJECTION_SIMPLIFIED_ANALYSIS', 'DEATH_BENEFIT_REJECTION_FIRST_ANALYSIS', 'DEATH_BENEFIT_REJECTION_INSS_DECISION_ANALYSIS', 'DEATH_BENEFIT_REJECTION_RURAL_TIME_ANALYSIS', 'DEATH_BENEFIT_REJECTION_MILITARY_SERVICE_ANALYSIS', 'DEATH_BENEFIT_REJECTION_PUBLIC_SERVICE_ANALYSIS', 'DEATH_BENEFIT_REJECTION_CTPS_OUTSIDE_CNIS_ANALYSIS', 'DEATH_BENEFIT_REJECTION_STUDENT_APPRENTICE_ANALYSIS', 'DEATH_BENEFIT_REJECTION_WORK_ABROAD_ANALYSIS', 'DEATH_BENEFIT_REJECTION_INFORMAL_WORK_ANALYSIS', 'DEATH_BENEFIT_REJECTION_LABOR_COURT_DECISION_ANALYSIS', 'REGULATORY_UPDATES', 'TEMPORARY_DISABILITY_BENEFITS_GRANT_COMPLETE_ANALYSIS', 'TEMPORARY_DISABILITY_BENEFITS_GRANT_SIMPLIFIED_ANALYSIS', 'TEMPORARY_DISABILITY_BENEFITS_GRANT_FIRST_ANALYSIS', 'SURVIVOR_PENSION_ANALYSIS_COMPLETE_ANALYSIS', 'SURVIVOR_PENSION_ANALYSIS_RETIREMENT_RULES', 'SURVIVOR_PENSION_ANALYSIS_DEPENDENT_PENSION_ANALYSES', 'SURVIVOR_PENSION_ANALYSIS_COMPLETE_ANALYSIS_TEXT', 'SURVIVOR_PENSION_ANALYSIS_SIMPLIFIED_ANALYSIS_TEXT', 'GENERAL_URBAN_RETIREMENT_DENIAL_COMPLETE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_SIMPLIFIED_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_INSS_DECISION_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_FIRST_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_RURAL_TIME_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_MILITARY_SERVICE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_PUBLIC_SERVICE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_CTPS_OUTSIDE_CNIS_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_STUDENT_APPRENTICE_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_WORK_ABROAD_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_INFORMAL_WORK_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_LABOR_COURT_DECISION_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_PPP_ANALYSIS', 'GENERAL_URBAN_RETIREMENT_DENIAL_COMPARE_CNIS_CTPS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_COMPLETE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_SIMPLIFIED_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_INSS_DECISION_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_FIRST_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_RURAL_TIME_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_MILITARY_SERVICE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_PUBLIC_SERVICE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_CTPS_OUTSIDE_CNIS_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_STUDENT_APPRENTICE_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_WORK_ABROAD_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_INFORMAL_WORK_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_LABOR_COURT_DECISION_ANALYSIS', 'DISABILITY_RETIREMENT_PLANNING_REJECTION_PPP_ANALYSIS', 'BPC_ELDERLY_ANALYSIS_COMPLETE_ANALYSIS', 'BPC_ELDERLY_ANALYSIS_SIMPLIFIED_ANALYSIS') NOT NULL`,
    );
    await queryRunner.query(
      `DROP INDEX \`REL_18f678ea101ff58294df2071e0\` ON \`temporary_incapacity_benefit_rejection\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temporary_incapacity_benefit_rejection\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temporary_incapacity_benefit_rejection_work_periods\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temp_incapacity_benefit_rejection_work_periods_earnings_history\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temporary_incapacity_benefit_rejection_result\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temporary_incapacity_benefit_rejection_insured_status\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temp_incapacity_benefit_rejection_insured_status_document\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temporary_incapacity_benefit_rejection_inss_benefit\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temporary_incapacity_benefit_rejection_document\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temporary_incapacity_benefit_rejection_disability_analysis\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temp_incapacity_benefit_rejection_disability_analysis_doc\``,
    );
    await queryRunner.query(
      `DROP TABLE \`temporary_incapacity_benefit_rejection_disability_analysis_cid\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` DROP COLUMN \`temporary_incapacity_benefit_rejection_id\``,
    );
  }
}
