import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AccidentAssistanceTerminated1777061052748 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Tabela principal
    await queryRunner.query(`CREATE TABLE \`accident_assistance_terminated\` (
      \`id\` varchar(36) NOT NULL,
      \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
      \`deleted_at\` datetime(6) NULL,
      \`accident_date\` date NULL,
      \`accident_description\` text NULL,
      \`der\` date NOT NULL,
      \`denial_date\` date NOT NULL,
      \`category\` varchar(100) NOT NULL,
      \`inss_password\` varchar(255) NULL,
      \`analysis_name\` varchar(255) NULL,
      \`benefit_cessation_reason\` text NOT NULL,
      \`had_previous_incapacity_benefit\` tinyint NOT NULL,
      \`previous_incapacity_benefit_number\` varchar(50) NULL,
      \`previous_incapacity_benefit_start_date\` date NULL,
      \`previous_incapacity_benefit_end_date\` date NULL,
      \`extension_request_status\` varchar(50) NULL,
      \`dib\` date NULL,
      \`dcb\` date NULL,
      \`inss_benefit_number\` varchar(255) NULL,
      \`accident_assistance_terminated_result_id\` varchar(36) NULL,
      \`created_by_id\` varchar(36) NULL,
      \`updated_by_id\` varchar(36) NULL,
      PRIMARY KEY (\`id\`)
    ) ENGINE=InnoDB`);

    // Tabela de benefícios
    await queryRunner.query(`CREATE TABLE \`accident_assistance_terminated_benefit\` (
      \`id\` varchar(36) NOT NULL,
      \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
      \`deleted_at\` datetime(6) NULL,
      \`inss_benefit_number\` varchar(100) NOT NULL,
      \`accident_assistance_terminated_id\` varchar(36) NULL,
      PRIMARY KEY (\`id\`)
    ) ENGINE=InnoDB`);

    // Tabela de CID
    await queryRunner.query(`CREATE TABLE \`accident_assistance_terminated_cid\` (
      \`id\` varchar(36) NOT NULL,
      \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
      \`deleted_at\` datetime(6) NULL,
      \`name\` varchar(20) NOT NULL,
      \`accident_assistance_terminated_id\` varchar(36) NULL,
      PRIMARY KEY (\`id\`)
    ) ENGINE=InnoDB`);

    // Tabela de documentos
    await queryRunner.query(`CREATE TABLE \`accident_assistance_terminated_document\` (
      \`id\` varchar(36) NOT NULL,
      \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
      \`deleted_at\` datetime(6) NULL,
      \`document\` varchar(255) NOT NULL,
      \`type\` enum('CNIS','ADMINISTRATIVE_PROCESS','OTHER') NOT NULL,
      \`accident_assistance_terminated_id\` varchar(36) NULL,
      PRIMARY KEY (\`id\`)
    ) ENGINE=InnoDB`);

    // Tabela de processos judiciais
    await queryRunner.query(`CREATE TABLE \`accident_assistance_terminated_legal_proceeding\` (
      \`id\` varchar(36) NOT NULL,
      \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
      \`deleted_at\` datetime(6) NULL,
      \`legal_proceeding_number\` varchar(100) NOT NULL,
      \`accident_assistance_terminated_id\` varchar(36) NULL,
      PRIMARY KEY (\`id\`)
    ) ENGINE=InnoDB`);

    // Tabela de períodos
    await queryRunner.query(`CREATE TABLE \`accident_assistance_terminated_period\` (
      \`id\` varchar(36) NOT NULL,
      \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
      \`deleted_at\` datetime(6) NULL,
      \`sequencial\` int NULL,
      \`period_name\` varchar(255) NULL,
      \`period_start\` date NULL,
      \`period_end\` date NULL,
      \`category\` varchar(100) NULL,
      \`is_pendency\` tinyint(1) NULL,
      \`reason_pendency\` enum('NO_CONTRIBUTION','NO_REGISTRATION','NO_CAR','NO_CTPS','NO_CADASTRAL_LINK','NO_CADASTRAL_LINK_AND_NO_CONTRIBUTION','NO_CONTRIBUTION_AND_NO_CTPS','NO_CONTRIBUTION_AND_NO_REGISTRATION','NO_CONTRIBUTION_AND_NO_CAR','NO_CONTRIBUTION_AND_NO_CADASTRAL_LINK','NO_CONTRIBUTION_AND_NO_CADASTRAL_LINK_AND_NO_CTPS','NO_CONTRIBUTION_AND_NO_CADASTRAL_LINK_AND_NO_REGISTRATION','NO_CONTRIBUTION_AND_NO_CADASTRAL_LINK_AND_NO_CAR','NO_CONTRIBUTION_AND_NO_CADASTRAL_LINK_AND_NO_CTPS_AND_NO_REGISTRATION','NO_CONTRIBUTION_AND_NO_CADASTRAL_LINK_AND_NO_CTPS_AND_NO_CAR','NO_CONTRIBUTION_AND_NO_CADASTRAL_LINK_AND_NO_REGISTRATION_AND_NO_CAR','NO_CONTRIBUTION_AND_NO_CADASTRAL_LINK_AND_NO_CTPS_AND_NO_REGISTRATION_AND_NO_CAR','OTHER') NULL,
      \`competence_below_the_minimum\` tinyint(1) NULL,
      \`contribution_average\` decimal(10,2) NULL,
      \`type_of_contribution\` varchar(100) NULL,
      \`status\` tinyint(1) NULL,
      \`accident_assistance_terminated_id\` varchar(36) NULL,
      PRIMARY KEY (\`id\`)
    ) ENGINE=InnoDB`);

    // Tabela de resultados
    await queryRunner.query(`CREATE TABLE \`accident_assistance_terminated_result\` (
      \`id\` varchar(36) NOT NULL,
      \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
      \`deleted_at\` datetime(6) NULL,
      \`accident_assistance_terminated_complete_analysis\` longtext NULL,
      \`accident_assistance_terminated_simplified_analysis\` text NULL,
      \`decision_details\` longtext NULL,
      \`first_analysis\` longtext NULL,
      PRIMARY KEY (\`id\`)
    ) ENGINE=InnoDB`);

    // Foreign keys
    await queryRunner.query(
      `ALTER TABLE \`accident_assistance_terminated\` ADD CONSTRAINT \`FK_accident_assistance_terminated_result\` FOREIGN KEY (\`accident_assistance_terminated_result_id\`) REFERENCES \`accident_assistance_terminated_result\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`accident_assistance_terminated_benefit\` ADD CONSTRAINT \`FK_accident_assistance_terminated_benefit_parent\` FOREIGN KEY (\`accident_assistance_terminated_id\`) REFERENCES \`accident_assistance_terminated\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`accident_assistance_terminated_cid\` ADD CONSTRAINT \`FK_accident_assistance_terminated_cid_parent\` FOREIGN KEY (\`accident_assistance_terminated_id\`) REFERENCES \`accident_assistance_terminated\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`accident_assistance_terminated_document\` ADD CONSTRAINT \`FK_accident_assistance_terminated_document_parent\` FOREIGN KEY (\`accident_assistance_terminated_id\`) REFERENCES \`accident_assistance_terminated\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`accident_assistance_terminated_legal_proceeding\` ADD CONSTRAINT \`FK_accident_assistance_terminated_legal_proceeding_parent\` FOREIGN KEY (\`accident_assistance_terminated_id\`) REFERENCES \`accident_assistance_terminated\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`accident_assistance_terminated_period\` ADD CONSTRAINT \`FK_accident_assistance_terminated_period_parent\` FOREIGN KEY (\`accident_assistance_terminated_id\`) REFERENCES \`accident_assistance_terminated\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    // Integração com analysis_tool_record
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` ADD COLUMN \`accident_assistance_terminated_id\` varchar(36) NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_analysis_tool_record_accident_assistance_terminated\` FOREIGN KEY (\`accident_assistance_terminated_id\`) REFERENCES \`accident_assistance_terminated\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`,
    );

    await queryRunner.query(
      `ALTER TABLE \`payment_plan_paid_resource\` CHANGE \`resource\` \`resource\` enum(   
        'LEGAL_PLEADING_COMPLETE_ANALYSIS',
        'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS',
        'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS',
        'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS',
        'TEACHER_RETIREMENT_PLANNING_COMPLETE_ANALYSIS',
        'TEACHER_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS',
        'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS',
        'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'LEGAL_PROCEEDING_MONITORING',
        'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS',
        'ELOY_CHAT_LEGISLATION_QUESTIONS',
        'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH',
        'ELOY_CHAT_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS',
        'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS',
        'SPECIAL_ACTIVITY_COMPLETE_ANALYSIS',
        'SPECIAL_ACTIVITY_SIMPLIFIED_ANALYSIS',
        'SPECIAL_RETIREMENT_GRANT_COMPLETE_ANALYSIS',
        'SPECIAL_RETIREMENT_GRANT_SIMPLIFIED_ANALYSIS',
        'SPECIAL_RETIREMENT_GRANT_FIRST_ANALYSIS',
        'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS',
        'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS',
        'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'MEDICAL_QUESTION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'MEDICAL_QUESTION_GENERATOR_COMPLETE_ANALYSIS',
        'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_COMPLETE_ANALYSIS',
        'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'SPEECH_GENERATOR_COMPLETE_ANALYSIS',
        'SPEECH_GENERATOR_SIMPLIFIED_ANALYSIS',
        'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS',
        'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS',
        'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'INSURANCE_QUALITY_ANALYSIS_COMPLETE_ANALYSIS',
        'INSURANCE_QUALITY_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'INITIAL_PETITION_GENERATOR_COMPLETE_ANALYSIS',
        'INITIAL_PETITION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'ADMINISTRATIVE_REQUEST_GENERATOR_COMPLETE_ANALYSIS',
        'ADMINISTRATIVE_REQUEST_GENERATOR_SIMPLIFIED_ANALYSIS',
        'FULL_OPINION_GENERATOR_COMPLETE_ANALYSIS',
        'FULL_OPINION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_COMPLETE_ANALYSIS',
        'RURAL_TIMELINE_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_INDIVIDUAL_PERIOD_DOCUMENT_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_PERIOD_DOCUMENT_ANALYSIS',
        'AUDIENCE_QUESTIONS_GENERATOR_COMPLETE_ANALYSIS',
        'AUDIENCE_QUESTIONS_GENERATOR_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_CONSOLIDATED_DOCUMENT_ANALYSIS',
        'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_IMPACT_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_CNIS_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_COMPARE_CNIS_CTPS',
        'GENERAL_URBAN_RETIREMENT_GRANT_SPECIAL_PERIOD_PPP_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_NO_END_DATE_DOCUMENTS_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_RURAL_TIME_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_MILITARY_SERVICE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_PUBLIC_SERVICE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_STUDENT_APPRENTICE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_WORK_ABROAD_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_INFORMAL_WORK_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_LABOR_COURT_DECISION_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_COMPLETE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_GRANT_SIMPLIFIED_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_COMPLETE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_SIMPLIFIED_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_ADMINISTRATIVE_REQUEST_DENIED_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_BENEFIT_AWARD_LETTER_ANALYSIS',
        'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_ADJUSTMENT_SIMULATION',
        'TEACHER_ADMINISTRATIVE_PROCESS_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_COMPLETE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_ADMINISTRATIVE_PROCESS_ANALYSIS',
        'SPECIAL_CATEGORY_RETIREMENT_COMPLETE_ANALYSIS',
        'SPECIAL_CATEGORY_RETIREMENT_SIMPLIFIED_ANALYSIS',
        'SPECIAL_CATEGORY_RETIREMENT_CONVERSION_ANALYSIS',
        'SPECIAL_CATEGORY_RETIREMENT_RULES_ANALYSIS',
        'SPECIAL_CATEGORY_RETIREMENT_ADMINISTRATIVE_PROCEDURE_ANALYSIS',
        'MINI_ADVISOR_COMPLETE_ANALYSIS',
        'MINI_ADVISOR_SIMPLIFIED_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_COMPLETE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_SIMPLIFIED_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_FIRST_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_RURAL_TIME_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_MILITARY_SERVICE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_PUBLIC_SERVICE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_STUDENT_APPRENTICE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_WORK_ABROAD_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_INFORMAL_WORK_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_LABOR_COURT_DECISION_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_GRANT_PPP_ANALYSIS',
        'DEATH_BENEFIT_GRANT_COMPLETE_ANALYSIS',
        'DEATH_BENEFIT_GRANT_SIMPLIFIED_ANALYSIS',
        'DEATH_BENEFIT_GRANT_FIRST_ANALYSIS',
        'DEATH_BENEFIT_GRANT_RURAL_TIME_ANALYSIS',
        'DEATH_BENEFIT_GRANT_MILITARY_SERVICE_ANALYSIS',
        'DEATH_BENEFIT_GRANT_PUBLIC_SERVICE_ANALYSIS',
        'DEATH_BENEFIT_GRANT_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'DEATH_BENEFIT_GRANT_STUDENT_APPRENTICE_ANALYSIS',
        'DEATH_BENEFIT_GRANT_WORK_ABROAD_ANALYSIS',
        'DEATH_BENEFIT_GRANT_INFORMAL_WORK_ANALYSIS',
        'DEATH_BENEFIT_GRANT_LABOR_COURT_DECISION_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_COMPLETE_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_SIMPLIFIED_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_FIRST_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_INSS_DECISION_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_RURAL_TIME_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_MILITARY_SERVICE_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_PUBLIC_SERVICE_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_STUDENT_APPRENTICE_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_WORK_ABROAD_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_INFORMAL_WORK_ANALYSIS',
        'DEATH_BENEFIT_REJECTION_LABOR_COURT_DECISION_ANALYSIS',
        'REGULATORY_UPDATES',
        'TEMPORARY_DISABILITY_BENEFITS_GRANT_COMPLETE_ANALYSIS',
        'TEMPORARY_DISABILITY_BENEFITS_GRANT_SIMPLIFIED_ANALYSIS',
        'TEMPORARY_DISABILITY_BENEFITS_GRANT_FIRST_ANALYSIS',
        'RURAL_OR_HYBRID_RETIREMENT_REJECTION_FIRST_ANALYSIS',
        'RURAL_OR_HYBRID_RETIREMENT_REJECTION_COMPLETE_ANALYSIS',
        'RURAL_OR_HYBRID_RETIREMENT_REJECTION_SIMPLIFIED_ANALYSIS',
        'RURAL_OR_HYBRID_RETIREMENT_REJECTION_WORK_PERIOD_DOCUMENT_ANALYSIS',
        'TIME_ACCELERATOR_RURAL_TIME_ANALYSIS',
        'TIME_ACCELERATOR_MILITARY_SERVICE_ANALYSIS',
        'TIME_ACCELERATOR_PUBLIC_SERVICE_ANALYSIS',
        'TIME_ACCELERATOR_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'TIME_ACCELERATOR_STUDENT_APPRENTICE_ANALYSIS',
        'TIME_ACCELERATOR_WORK_ABROAD_ANALYSIS',
        'TIME_ACCELERATOR_INFORMAL_WORK_ANALYSIS',
        'TIME_ACCELERATOR_LABOR_COURT_DECISION_ANALYSIS',
        'SURVIVOR_PENSION_ANALYSIS_COMPLETE_ANALYSIS',
        'SURVIVOR_PENSION_ANALYSIS_RETIREMENT_RULES',
        'SURVIVOR_PENSION_ANALYSIS_DEPENDENT_PENSION_ANALYSES',
        'SURVIVOR_PENSION_ANALYSIS_COMPLETE_ANALYSIS_TEXT',
        'SURVIVOR_PENSION_ANALYSIS_SIMPLIFIED_ANALYSIS_TEXT',
        'GENERAL_URBAN_RETIREMENT_DENIAL_COMPLETE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_SIMPLIFIED_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_INSS_DECISION_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_FIRST_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_RURAL_TIME_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_MILITARY_SERVICE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_PUBLIC_SERVICE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_STUDENT_APPRENTICE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_WORK_ABROAD_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_INFORMAL_WORK_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_LABOR_COURT_DECISION_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_PPP_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_DENIAL_COMPARE_CNIS_CTPS',
        'ACCIDENT_BENEFIT_REJECTION_FIRST_ANALYSIS',
        'ACCIDENT_BENEFIT_REJECTION_SECOND_ANALYSIS',
        'ACCIDENT_BENEFIT_REJECTION_COMPLETE_ANALYSIS',
        'ACCIDENT_BENEFIT_REJECTION_SIMPLIFIED_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_COMPLETE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_SIMPLIFIED_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_INSS_DECISION_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_FIRST_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_RURAL_TIME_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_MILITARY_SERVICE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_PUBLIC_SERVICE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_STUDENT_APPRENTICE_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_WORK_ABROAD_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_INFORMAL_WORK_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_LABOR_COURT_DECISION_ANALYSIS',
        'DISABILITY_RETIREMENT_PLANNING_REJECTION_PPP_ANALYSIS',
        'BPC_DISABILITY_DENIAL_COMPLETE_ANALYSIS',
        'BPC_DISABILITY_DENIAL_SIMPLIFIED_ANALYSIS',
        'BPC_DISABILITY_DENIAL_INSS_DECISION_ANALYSIS',
        'BPC_DISABILITY_DENIAL_FIRST_ANALYSIS',
        'BPC_ELDERLY_ANALYSIS_COMPLETE_ANALYSIS',
        'BPC_ELDERLY_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'TEMPORARY_INCAPACITY_BENEFIT_REJECTION_INSS_DECISION_ANALYSIS',
        'TEMPORARY_INCAPACITY_BENEFIT_REJECTION_FIRST_ANALYSIS',
        'TEMPORARY_INCAPACITY_BENEFIT_REJECTION_COMPLETE_ANALYSIS',
        'TEMPORARY_INCAPACITY_BENEFIT_REJECTION_SIMPLIFIED_ANALYSIS',
        'MATERNITY_PAY_GRANT_FIRST_ANALYSIS',
        'MATERNITY_PAY_GRANT_COMPLETE_ANALYSIS',
        'MATERNITY_PAY_GRANT_SIMPLIFIED_ANALYSIS',
        'ACCIDENT_ASSISTANCE_TERMINATED_COMPLETE_ANALYSIS',
        'ACCIDENT_ASSISTANCE_TERMINATED_SIMPLIFIED_ANALYSIS',
        'ACCIDENT_ASSISTANCE_TERMINATED_DECISION_DETAILS',
        'ACCIDENT_ASSISTANCE_TERMINATED_FIRST_ANALYSIS') NOT NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop FKs analysis_tool_record
    await queryRunner.query(
      'ALTER TABLE `analysis_tool_record` DROP FOREIGN KEY `FK_analysis_tool_record_accident_assistance_terminated`',
    );
    await queryRunner.query(
      'ALTER TABLE `analysis_tool_record` DROP COLUMN `accident_assistance_terminated_id`',
    );

    // Drop FKs filhos
    await queryRunner.query(
      'ALTER TABLE `accident_assistance_terminated_period` DROP FOREIGN KEY `FK_accident_assistance_terminated_period_parent`',
    );
    await queryRunner.query(
      'ALTER TABLE `accident_assistance_terminated_legal_proceeding` DROP FOREIGN KEY `FK_accident_assistance_terminated_legal_proceeding_parent`',
    );
    await queryRunner.query(
      'ALTER TABLE `accident_assistance_terminated_document` DROP FOREIGN KEY `FK_accident_assistance_terminated_document_parent`',
    );
    await queryRunner.query(
      'ALTER TABLE `accident_assistance_terminated_cid` DROP FOREIGN KEY `FK_accident_assistance_terminated_cid_parent`',
    );
    await queryRunner.query(
      'ALTER TABLE `accident_assistance_terminated_benefit` DROP FOREIGN KEY `FK_accident_assistance_terminated_benefit_parent`',
    );
    await queryRunner.query(
      'ALTER TABLE `accident_assistance_terminated` DROP FOREIGN KEY `FK_accident_assistance_terminated_result`',
    );

    // Drop tables em ordem reversa
    await queryRunner.query(
      'DROP TABLE IF EXISTS `accident_assistance_terminated_result`',
    );
    await queryRunner.query(
      'DROP TABLE IF EXISTS `accident_assistance_terminated_period`',
    );
    await queryRunner.query(
      'DROP TABLE IF EXISTS `accident_assistance_terminated_legal_proceeding`',
    );
    await queryRunner.query(
      'DROP TABLE IF EXISTS `accident_assistance_terminated_document`',
    );
    await queryRunner.query(
      'DROP TABLE IF EXISTS `accident_assistance_terminated_cid`',
    );
    await queryRunner.query(
      'DROP TABLE IF EXISTS `accident_assistance_terminated_benefit`',
    );
    await queryRunner.query(
      'DROP TABLE IF EXISTS `accident_assistance_terminated`',
    );
  }
}
