import { MigrationInterface, QueryRunner } from "typeorm";

export class AddInssBenefitNumberToAccidentAssistanceTerminated1777317806734 implements MigrationInterface {
    name = 'AddInssBenefitNumberToAccidentAssistanceTerminated1777317806734'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_cfbbaafae7a8df980f0f21a2a3\` ON \`auth_identity\``);
        await queryRunner.query(`DROP INDEX \`FK_6acdbf254bed5eb62d4d54958d3\` ON \`death_benefit_grant_document\``);
        await queryRunner.query(`DROP INDEX \`FK_death_benefit_grant_time_accelerator_death_benefit_grant\` ON \`death_benefit_grant_time_accelerator\``);
        await queryRunner.query(`DROP INDEX \`FK_maternity_pay_grant_document_to_grant\` ON \`maternity_pay_grant_document\``);
        await queryRunner.query(`DROP INDEX \`FK_maternity_pay_grant_period_document_to_period\` ON \`maternity_pay_grant_period_document\``);
        await queryRunner.query(`DROP INDEX \`FK_maternity_pay_grant_period_to_grant\` ON \`maternity_pay_grant_period\``);
        await queryRunner.query(`DROP INDEX \`FK_maternity_pay_grant_earnings_history_to_grant\` ON \`maternity_pay_grant_earnings_history\``);
        await queryRunner.query(`DROP INDEX \`FK_maternity_pay_grant_earnings_history_to_period\` ON \`maternity_pay_grant_earnings_history\``);
        await queryRunner.query(`DROP INDEX \`FK_maternity_pay_grant_inss_benefit_to_grant\` ON \`maternity_pay_grant_inss_benefit\``);
        await queryRunner.query(`DROP INDEX \`FK_maternity_pay_grant_legal_proceeding_to_grant\` ON \`maternity_pay_grant_legal_proceeding\``);
        await queryRunner.query(`DROP INDEX \`IDX_aa52d2c2319dfd0c8d690b1291\` ON \`maternity_pay_grant\``);
        await queryRunner.query(`DROP INDEX \`FK_pending_exit_date_cnis_contribution_period\` ON \`rural_timeline_period_pending_exit_date\``);
        await queryRunner.query(`DROP INDEX \`FK_cnis_contribution_period_document_period\` ON \`rural_timeline_cnis_contribution_period_document\``);
        await queryRunner.query(`DROP INDEX \`FK_overdue_contribution_cnis_contribution_period\` ON \`rural_timeline_cnis_contribution_period_overdue_contribution\``);
        await queryRunner.query(`DROP INDEX \`IDX_special_retirement_grant_period_observation_period\` ON \`special_retirement_grant_period_observation\``);
        await queryRunner.query(`DROP INDEX \`FK_c9430f87a08b094fde62807d974\` ON \`spa_benefit_originator_identification_document\``);
        await queryRunner.query(`DROP INDEX \`IDX_96690f1ed7525214faa3c3d1bf\` ON \`spa_benefit_originator_identification\``);
        await queryRunner.query(`DROP INDEX \`REL_1f9bbd7929d29a60fa18efbfa7\` ON \`spa_benefit_originator_identification\``);
        await queryRunner.query(`DROP INDEX \`FK_5a40eca4f2b9a31b502dadc419a\` ON \`spa_customer_profile_identification_document\``);
        await queryRunner.query(`DROP INDEX \`IDX_27e61c7381b787e99c3138290e\` ON \`spa_customer_profile_identification\``);
        await queryRunner.query(`DROP INDEX \`REL_e5d13c0b0ff4fc0aac9c0bd3f1\` ON \`spa_customer_profile_identification\``);
        await queryRunner.query(`DROP INDEX \`FK_fe13f7fc78a045ab3ba03df35db\` ON \`spa_deceased_benefit_dependents_document\``);
        await queryRunner.query(`DROP INDEX \`FK_a68932b69afdb1df547c3959637\` ON \`spa_deceased_benefit_dependents\``);
        await queryRunner.query(`DROP INDEX \`FK_351b571298612eb99f1480abf0a\` ON \`spa_deceased_work_history_period_document\``);
        await queryRunner.query(`DROP INDEX \`FK_88e4f2a0e52506a4b818a094384\` ON \`spa_deceased_work_history_period\``);
        await queryRunner.query(`DROP INDEX \`IDX_15d388f0d60f9d5bd1db425775\` ON \`spa_deceased_work_history\``);
        await queryRunner.query(`DROP INDEX \`REL_02952d3df1d2f65220433900c6\` ON \`spa_deceased_work_history\``);
        await queryRunner.query(`DROP INDEX \`FK_563c83aa0b7d476ceb7e38f2bcc\` ON \`spa_result_dependent_pension_analysis\``);
        await queryRunner.query(`DROP INDEX \`FK_f44913cb29a2e09a7e37a055607\` ON \`spa_result_retirement_rule\``);
        await queryRunner.query(`DROP INDEX \`IDX_9059fa1c6af64371b60a843836\` ON \`spa_result\``);
        await queryRunner.query(`DROP INDEX \`REL_c07a04bf5030365523fe0475a7\` ON \`spa_result\``);
        await queryRunner.query(`DROP INDEX \`IDX_0dbf09f864fc1d0b259a49b471\` ON \`temporary_disability_benefits_grant\``);
        await queryRunner.query(`DROP INDEX \`REL_tdbg_to_result\` ON \`temporary_disability_benefits_grant\``);
        await queryRunner.query(`DROP INDEX \`FK_40b7c5c5f6f722d303f7866fb10\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`FK_analysis_tool_record_to_maternity_pay_grant\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`FK_d1ca0140d8785f268c506bd8f84\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`IDX_2e2cb32e1168368c156782d993\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`IDX_467461f25aaf1080665789dfd2\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`IDX_4bf0d6a2aa0890f504095a6986\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`IDX_a11ef687a9c70fdd9d958e2942\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`IDX_cdb9ee6d20c2c9321c1af765fe\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`IDX_d839be03e3ce21bd911d1add88\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`IDX_de48ccd1c2a2087b6f247f298d\` ON \`analysis_tool_record\``);
        await queryRunner.query(`DROP INDEX \`bank_external_id\` ON \`bank_transfer\``);
        await queryRunner.query(`DROP INDEX \`FK_affiliate_customer_payment_plan_affiliate_customer_id\` ON \`affiliate_customer_payment_plan\``);
        await queryRunner.query(`DROP INDEX \`FK_affiliate_customer_payment_plan_payment_plan_id\` ON \`affiliate_customer_payment_plan\``);
        await queryRunner.query(`DROP INDEX \`FK_affiliate_customer_customer_id\` ON \`affiliate_customer\``);
        await queryRunner.query(`DROP INDEX \`FK_opp_affiliate_commission_affiliate\` ON \`organization_payment_plan_affiliate_commission\``);
        await queryRunner.query(`DROP INDEX \`UQ_opp_affiliate_commission_plan\` ON \`organization_payment_plan_affiliate_commission\``);
        await queryRunner.query(`DROP INDEX \`FK_abt_bank_transfer\` ON \`affiliate_bank_transfer\``);
        await queryRunner.query(`DROP INDEX \`FK_abt_commission\` ON \`affiliate_bank_transfer\``);
        await queryRunner.query(`DROP INDEX \`UQ_abt_bank_payment\` ON \`affiliate_bank_transfer\``);
        await queryRunner.query(`DROP INDEX \`FK_org_customization_footer_template\` ON \`organization_customization\``);
        await queryRunner.query(`DROP INDEX \`FK_org_customization_header_template\` ON \`organization_customization\``);
        await queryRunner.query(`DROP INDEX \`FK_org_customization_organization\` ON \`organization_customization\``);
        await queryRunner.query(`DROP INDEX \`FK_rtccp_adjustment_period\` ON \`rural_timeline_cnis_contribution_period_adjustment\``);
        await queryRunner.query(`DROP INDEX \`FK_system_activities_analysis_tool_client\` ON \`system_activities\``);
        await queryRunner.query(`DROP INDEX \`FK_system_activities_analysis_tool_record\` ON \`system_activities\``);
        await queryRunner.query(`DROP INDEX \`FK_system_activities_organization_member\` ON \`system_activities\``);
        await queryRunner.query(`DROP INDEX \`UQ_acc_config\` ON \`affiliate_customer_config\``);
        await queryRunner.query(`DROP INDEX \`FK_364942f94d78d35288f43ece6d7\` ON \`customer_email_sent\``);
        await queryRunner.query(`DROP INDEX \`FK_customer_email_sent_attachment_analysis_tool_record\` ON \`customer_email_sent_attachment\``);
        await queryRunner.query(`DROP INDEX \`FK_customer_email_sent_attachment_customer_email_sent\` ON \`customer_email_sent_attachment\``);
        await queryRunner.query(`DROP INDEX \`FK_email_template_owner\` ON \`email_template\``);
        await queryRunner.query(`ALTER TABLE \`accident_assistance_terminated\` ADD \`inss_benefit_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_institutor\` ADD CONSTRAINT \`FK_b63271a1053b7195bc52d735060\` FOREIGN KEY (\`death_benefit_rejection_id\`) REFERENCES \`death_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_legal_proceeding\` ADD CONSTRAINT \`FK_ff5bedc3bc8d85de8d1520574c4\` FOREIGN KEY (\`death_benefit_rejection_id\`) REFERENCES \`death_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_legal_representative\` ADD CONSTRAINT \`FK_6f01cefbbb65db41c984ea69748\` FOREIGN KEY (\`death_benefit_rejection_id\`) REFERENCES \`death_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_period_earnings_history\` ADD CONSTRAINT \`FK_f03f2a6d1751e879a38760934cb\` FOREIGN KEY (\`death_benefit_rejection_period_id\`) REFERENCES \`death_benefit_rejection_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_period\` ADD CONSTRAINT \`FK_941ec829e4900ede71b3541794b\` FOREIGN KEY (\`death_benefit_rejection_id\`) REFERENCES \`death_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_period_document\` ADD CONSTRAINT \`FK_b5f448c6fe6fd536fe79810ffbc\` FOREIGN KEY (\`death_benefit_rejection_period_id\`) REFERENCES \`death_benefit_rejection_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_time_accelerator\` ADD CONSTRAINT \`FK_cb8631b016f91dd23dfc9b708b6\` FOREIGN KEY (\`death_benefit_rejection_id\`) REFERENCES \`death_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection\` ADD CONSTRAINT \`FK_b5ab738cfd5f6f3dbfeda05866a\` FOREIGN KEY (\`death_benefit_rejection_result_id\`) REFERENCES \`death_benefit_rejection_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_disability_period_document\` ADD CONSTRAINT \`FK_a17c85655354f8fc894cdc428e6\` FOREIGN KEY (\`disability_retirement_planning_grant_disability_period_id\`) REFERENCES \`disability_retirement_planning_grant_disability_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_disability_period\` ADD CONSTRAINT \`FK_f4eeb9568b97846552caa7daa2b\` FOREIGN KEY (\`disability_retirement_planning_grant_id\`) REFERENCES \`disability_retirement_planning_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_document\` ADD CONSTRAINT \`FK_0d09c38b950a5d9375bc0e56ff7\` FOREIGN KEY (\`disability_retirement_planning_grant_id\`) REFERENCES \`disability_retirement_planning_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_inss_benefit\` ADD CONSTRAINT \`FK_1b6b36f2a052c9c39fb2070c542\` FOREIGN KEY (\`disability_retirement_planning_grant_id\`) REFERENCES \`disability_retirement_planning_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_legal_proceeding\` ADD CONSTRAINT \`FK_7d2a31f4f32b81929ca92e57841\` FOREIGN KEY (\`disability_retirement_planning_grant_id\`) REFERENCES \`disability_retirement_planning_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_period_document\` ADD CONSTRAINT \`FK_01286dee51034a4d9ca36d554d8\` FOREIGN KEY (\`disability_retirement_planning_grant_period_id\`) REFERENCES \`disability_retirement_planning_grant_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_period_earnings_history\` ADD CONSTRAINT \`FK_7cec18c7b75a792b7ef48219c72\` FOREIGN KEY (\`disability_retirement_planning_grant_period_id\`) REFERENCES \`disability_retirement_planning_grant_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_period\` ADD CONSTRAINT \`FK_8b0953dce38e733aad3c2b279f5\` FOREIGN KEY (\`disability_retirement_planning_grant_id\`) REFERENCES \`disability_retirement_planning_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_time_accelerator\` ADD CONSTRAINT \`FK_d7aa70164713ebce108a0772957\` FOREIGN KEY (\`disability_retirement_planning_grant_id\`) REFERENCES \`disability_retirement_planning_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant\` ADD CONSTRAINT \`FK_e01eb46945d56b38e24ab445a00\` FOREIGN KEY (\`disability_retirement_planning_grant_result_id\`) REFERENCES \`disability_retirement_planning_grant_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_document\` ADD CONSTRAINT \`FK_cfd8d7ee91314485f036e022f93\` FOREIGN KEY (\`disability_retirement_planning_rejection_id\`) REFERENCES \`disability_retirement_planning_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_inss_benefit\` ADD CONSTRAINT \`FK_d45a5e41daa6c2039df8c7aae71\` FOREIGN KEY (\`disability_retirement_planning_rejection_id\`) REFERENCES \`disability_retirement_planning_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_period_document\` ADD CONSTRAINT \`FK_4b8036052952e2fcae56cd6dc52\` FOREIGN KEY (\`disability_retirement_planning_rejection_period_id\`) REFERENCES \`disability_retirement_planning_rejection_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_period_earnings_history\` ADD CONSTRAINT \`FK_fd364b657fc89dbc8fada328faa\` FOREIGN KEY (\`disability_retirement_planning_rejection_period_id\`) REFERENCES \`disability_retirement_planning_rejection_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_period\` ADD CONSTRAINT \`FK_b45477ee3545060de55178a853c\` FOREIGN KEY (\`disability_retirement_planning_rejection_id\`) REFERENCES \`disability_retirement_planning_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_time_accelerator\` ADD CONSTRAINT \`FK_8dd2b57e0b2b392adff47cc1097\` FOREIGN KEY (\`disability_retirement_planning_rejection_id\`) REFERENCES \`disability_retirement_planning_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection\` ADD CONSTRAINT \`FK_f4473c093f619f933d389e0c27a\` FOREIGN KEY (\`disability_retirement_planning_rejection_result_id\`) REFERENCES \`disability_retirement_planning_rejection_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_document\` ADD CONSTRAINT \`FK_25ff45060081bc1f21612162545\` FOREIGN KEY (\`disability_retirement_planning_id\`) REFERENCES \`disability_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_inss_benefit\` ADD CONSTRAINT \`FK_c54e0d73ea5eee010607750f2f6\` FOREIGN KEY (\`disability_retirement_planning_id\`) REFERENCES \`disability_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_legal_proceeding\` ADD CONSTRAINT \`FK_93d315a1e03faee4ead93c642e6\` FOREIGN KEY (\`disability_retirement_planning_id\`) REFERENCES \`disability_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_disability_document\` ADD CONSTRAINT \`FK_3963237e6f03ccd2fa598e40302\` FOREIGN KEY (\`disability_retirement_planning_period_disability_id\`) REFERENCES \`disability_retirement_planning_period_disability\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_disability\` ADD CONSTRAINT \`FK_d545cc333ea61dd1ce9a5af4a76\` FOREIGN KEY (\`disability_retirement_planning_period_id\`) REFERENCES \`disability_retirement_planning_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_disability\` ADD CONSTRAINT \`FK_b205ea894cca82a9cd61b9ae332\` FOREIGN KEY (\`cid_ten_id\`) REFERENCES \`cid_ten\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_special_time_document\` ADD CONSTRAINT \`FK_f5ee414426e28fa5b1a2c2ffa1b\` FOREIGN KEY (\`disability_retirement_planning_period_special_time_id\`) REFERENCES \`disability_retirement_planning_period_special_time\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_special_time\` ADD CONSTRAINT \`FK_eae8f709d84f24cf350ab87d6a0\` FOREIGN KEY (\`disability_retirement_planning_period_id\`) REFERENCES \`disability_retirement_planning_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period\` ADD CONSTRAINT \`FK_52a6d25e0f0f5c9483e9a3874bb\` FOREIGN KEY (\`disability_retirement_planning_id\`) REFERENCES \`disability_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_remuneration\` ADD CONSTRAINT \`FK_68d222b182c48f73000090c6a63\` FOREIGN KEY (\`disability_retirement_planning_id\`) REFERENCES \`disability_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_result\` ADD CONSTRAINT \`FK_e2a966ef33036855d12187034cb\` FOREIGN KEY (\`disability_retirement_planning_id\`) REFERENCES \`disability_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning\` ADD CONSTRAINT \`FK_b111c1afd93ea457abc5f7b8518\` FOREIGN KEY (\`disability_retirement_planning_result_id\`) REFERENCES \`disability_retirement_planning_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_document\` ADD CONSTRAINT \`FK_2a3acf315c56d30ababa417dc71\` FOREIGN KEY (\`general_urban_retirement_denial_id\`) REFERENCES \`general_urban_retirement_denial\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_inss_benefit\` ADD CONSTRAINT \`FK_e4eeb546aacceda46a689d5d0f0\` FOREIGN KEY (\`general_urban_retirement_denial_id\`) REFERENCES \`general_urban_retirement_denial\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_period_document\` ADD CONSTRAINT \`FK_732df9bb577c2cd68663ce238e8\` FOREIGN KEY (\`general_urban_retirement_denial_period_id\`) REFERENCES \`general_urban_retirement_denial_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_period_earnings_history\` ADD CONSTRAINT \`FK_317128228030c9ae014697dace6\` FOREIGN KEY (\`general_urban_retirement_denial_period_id\`) REFERENCES \`general_urban_retirement_denial_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_period\` ADD CONSTRAINT \`FK_dd3f0d902061c919eae421420b0\` FOREIGN KEY (\`general_urban_retirement_denial_id\`) REFERENCES \`general_urban_retirement_denial\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_time_accelerator\` ADD CONSTRAINT \`FK_7517c3fc64dbe662f139a9b7c8a\` FOREIGN KEY (\`general_urban_retirement_denial_id\`) REFERENCES \`general_urban_retirement_denial\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial\` ADD CONSTRAINT \`FK_0f64511146e3bab49f0704c1ce6\` FOREIGN KEY (\`general_urban_retirement_denial_result_id\`) REFERENCES \`general_urban_retirement_denial_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_document\` ADD CONSTRAINT \`FK_9956520cfbc84b2291cf0e6d461\` FOREIGN KEY (\`maternity_pay_grant_id\`) REFERENCES \`maternity_pay_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_period_document\` ADD CONSTRAINT \`FK_4cb8f08b65f08b851da32327950\` FOREIGN KEY (\`maternity_pay_grant_period_id\`) REFERENCES \`maternity_pay_grant_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_period\` ADD CONSTRAINT \`FK_95bb8ac7b999ddc0aa9fd4e2cd0\` FOREIGN KEY (\`maternity_pay_grant_id\`) REFERENCES \`maternity_pay_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_earnings_history\` ADD CONSTRAINT \`FK_7e27529be9de63c2a096629d8f4\` FOREIGN KEY (\`maternity_pay_grant_id\`) REFERENCES \`maternity_pay_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_earnings_history\` ADD CONSTRAINT \`FK_736f2889e8b20d7578ce1bb98fc\` FOREIGN KEY (\`maternity_pay_grant_period_id\`) REFERENCES \`maternity_pay_grant_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_inss_benefit\` ADD CONSTRAINT \`FK_6f7c30501af6ebfe45089c3f4fc\` FOREIGN KEY (\`maternity_pay_grant_id\`) REFERENCES \`maternity_pay_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_legal_proceeding\` ADD CONSTRAINT \`FK_b1c2a28a03d2a672175a4b81671\` FOREIGN KEY (\`maternity_pay_grant_id\`) REFERENCES \`maternity_pay_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant\` ADD CONSTRAINT \`FK_aa52d2c2319dfd0c8d690b1291e\` FOREIGN KEY (\`maternity_pay_grant_result_id\`) REFERENCES \`maternity_pay_grant_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_document\` ADD CONSTRAINT \`FK_b9776cb99104d90b1d6386556df\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_inss_benefit\` ADD CONSTRAINT \`FK_de881f54db61539e8d3cd0992fa\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_legal_proceeding\` ADD CONSTRAINT \`FK_651e03f0fd195c3ea03c8f3abb6\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_period_document\` ADD CONSTRAINT \`FK_0e85e09ec4376dfc7a1b213ba3b\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_period_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_period_member_document\` ADD CONSTRAINT \`FK_b71d2e04f813a6444a51de3f973\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_period_member_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection_period_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_period_member\` ADD CONSTRAINT \`FK_3ed7eba9022a2f10ddd2296dc33\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_period_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_period\` ADD CONSTRAINT \`FK_7514e542f6eb2ef456d33151e86\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_testimonial_witness_doc\` ADD CONSTRAINT \`FK_35be67c51a0264c680bb74e9994\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_testimonial_witness_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection_testimonial_witness\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_testimonial_witness\` ADD CONSTRAINT \`FK_bf0db2c5dafafae97fac551d4c8\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_time_accelerator\` ADD CONSTRAINT \`FK_f21e8903bf2d3c66872391e1353\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_work_period_doc_analysis\` ADD CONSTRAINT \`FK_303558499eb1025e42af3f6ea66\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_work_period_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection_work_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_work_period_document\` ADD CONSTRAINT \`FK_7e0c17305ae532de862d6b2fd0d\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_work_period_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection_work_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_work_period_earnings_hist\` ADD CONSTRAINT \`FK_5a097bd29587cfab937318c4a0d\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_work_period_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection_work_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_work_period\` ADD CONSTRAINT \`FK_f06f95ab147865f33a78d59f882\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection\` ADD CONSTRAINT \`FK_9adce3a8ca303c6aa9f56ed21a4\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_result_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`special_retirement_grant_period_observation\` ADD CONSTRAINT \`FK_0567ebe9261dad30405d907e112\` FOREIGN KEY (\`special_retirement_grant_period_id\`) REFERENCES \`special_retirement_grant_period\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_benefit_originator_identification_document\` ADD CONSTRAINT \`FK_786ce267551df8e4b6640da52f6\` FOREIGN KEY (\`benefit_originator_identification_id\`) REFERENCES \`spa_benefit_originator_identification\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_benefit_originator_identification\` ADD CONSTRAINT \`FK_96690f1ed7525214faa3c3d1bf6\` FOREIGN KEY (\`survivor_pension_analysis_id\`) REFERENCES \`spa\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_customer_profile_identification_document\` ADD CONSTRAINT \`FK_40531007bc2fb0c2d65efa48f3b\` FOREIGN KEY (\`customer_profile_identification_id\`) REFERENCES \`spa_customer_profile_identification\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_customer_profile_identification\` ADD CONSTRAINT \`FK_27e61c7381b787e99c3138290e8\` FOREIGN KEY (\`survivor_pension_analysis_id\`) REFERENCES \`spa\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_benefit_dependents_document\` ADD CONSTRAINT \`FK_358c75ce90dec5fc870dbc4cca8\` FOREIGN KEY (\`deceased_benefit_dependents_id\`) REFERENCES \`spa_deceased_benefit_dependents\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_benefit_dependents\` ADD CONSTRAINT \`FK_3372c8549c0a75f2dc5726ebb65\` FOREIGN KEY (\`survivor_pension_analysis_id\`) REFERENCES \`spa\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_work_history_period_document\` ADD CONSTRAINT \`FK_8901176f40704205180a0410a55\` FOREIGN KEY (\`deceased_work_history_period_id\`) REFERENCES \`spa_deceased_work_history_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_work_history_period\` ADD CONSTRAINT \`FK_3a0c48a3fddccd6f523887b466e\` FOREIGN KEY (\`deceased_work_history_id\`) REFERENCES \`spa_deceased_work_history\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_work_history\` ADD CONSTRAINT \`FK_15d388f0d60f9d5bd1db4257754\` FOREIGN KEY (\`survivor_pension_analysis_id\`) REFERENCES \`spa\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_result_dependent_pension_analysis\` ADD CONSTRAINT \`FK_f18b17030c3bb40c859f7248b0e\` FOREIGN KEY (\`survivor_pension_analysis_result_id\`) REFERENCES \`spa_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_result_retirement_rule\` ADD CONSTRAINT \`FK_94122a13d4667f694982b80a2bf\` FOREIGN KEY (\`survivor_pension_analysis_result_id\`) REFERENCES \`spa_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`spa_result\` ADD CONSTRAINT \`FK_9059fa1c6af64371b60a843836c\` FOREIGN KEY (\`survivor_pension_analysis_id\`) REFERENCES \`spa\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_document\` ADD CONSTRAINT \`FK_5a7ef6d0bc6405f3e1862a59cc6\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_inss_benefit\` ADD CONSTRAINT \`FK_c3334211119f55686f6c82f4467\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_legal_proceeding\` ADD CONSTRAINT \`FK_b99de22ec91a8eb020729508a10\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period_item_document\` ADD CONSTRAINT \`FK_f390dcfeaecee81c424c6c858e0\` FOREIGN KEY (\`teacher_retirement_planning_period_item_id\`) REFERENCES \`teacher_retirement_planning_period_item\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period_item\` ADD CONSTRAINT \`FK_1d4aa88a09fcc00b5195c805f9f\` FOREIGN KEY (\`teacher_retirement_planning_period_id\`) REFERENCES \`teacher_retirement_planning_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period\` ADD CONSTRAINT \`FK_dda5b7c7d2034d4c63a53d748c6\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_remuneration\` ADD CONSTRAINT \`FK_d50a70e85425e4136767cf47bb4\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning\` ADD CONSTRAINT \`FK_5490dafb2d15ebb5d70278f6906\` FOREIGN KEY (\`teacher_retirement_planning_result_id\`) REFERENCES \`teacher_retirement_planning_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_document\` ADD CONSTRAINT \`FK_d495fdd8d01ad24f54fdbe5f2d9\` FOREIGN KEY (\`temporary_disability_benefits_grant_id\`) REFERENCES \`temporary_disability_benefits_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_inss_benefit\` ADD CONSTRAINT \`FK_24105a0e93c717b9300265c37a2\` FOREIGN KEY (\`temporary_disability_benefits_grant_id\`) REFERENCES \`temporary_disability_benefits_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_insured_status_document\` ADD CONSTRAINT \`FK_9cbb85fc671daa41b718f340c8b\` FOREIGN KEY (\`temporary_disability_benefits_grant_insured_status_id\`) REFERENCES \`temporary_disability_benefits_grant_insured_status\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_insured_status\` ADD CONSTRAINT \`FK_db51dcb6dee04079503bb287f76\` FOREIGN KEY (\`temporary_disability_benefits_grant_id\`) REFERENCES \`temporary_disability_benefits_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_legal_proceeding\` ADD CONSTRAINT \`FK_208b10b09994762bbcac8c3ecc9\` FOREIGN KEY (\`temporary_disability_benefits_grant_id\`) REFERENCES \`temporary_disability_benefits_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_period_document\` ADD CONSTRAINT \`FK_8d2c787f5a504f048ba926b77c2\` FOREIGN KEY (\`temporary_disability_benefits_grant_period_id\`) REFERENCES \`temporary_disability_benefits_grant_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_previous_benefits_document\` ADD CONSTRAINT \`FK_5bb5c3c3dc8f739464f9fe89ca7\` FOREIGN KEY (\`temporary_disability_benefits_grant_previous_benefits_id\`) REFERENCES \`temporary_disability_benefits_grant_previous_benefits\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_previous_benefits\` ADD CONSTRAINT \`FK_0a7fc9cd43165a6c11ea78a2238\` FOREIGN KEY (\`temporary_disability_benefits_grant_period_id\`) REFERENCES \`temporary_disability_benefits_grant_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_period\` ADD CONSTRAINT \`FK_8bd86f9501c9b24ef12a64358ee\` FOREIGN KEY (\`temporary_disability_benefits_grant_id\`) REFERENCES \`temporary_disability_benefits_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temp_disability_benefits_grant_work_periods_earnings_history\` ADD CONSTRAINT \`FK_fc84df6ddcd859b5de1e40c6764\` FOREIGN KEY (\`temporary_disability_benefits_grant_work_periods_id\`) REFERENCES \`temporary_disability_benefits_grant_work_periods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_work_periods\` ADD CONSTRAINT \`FK_d95c3786cfb90925d20ea9ced9e\` FOREIGN KEY (\`temporary_disability_benefits_grant_id\`) REFERENCES \`temporary_disability_benefits_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant\` ADD CONSTRAINT \`FK_0dbf09f864fc1d0b259a49b4719\` FOREIGN KEY (\`temporary_disability_benefits_grant_result_id\`) REFERENCES \`temporary_disability_benefits_grant_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_disability_analysis_cid\` ADD CONSTRAINT \`FK_40e5be3953da2de601571052fee\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_disability_analysis_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_disability_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temp_incapacity_benefit_rejection_disability_analysis_doc\` ADD CONSTRAINT \`FK_6cb96d0a7cff7ff205192fcb51e\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_disability_analysis_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_disability_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_disability_analysis\` ADD CONSTRAINT \`FK_2edec45b0b1f35c03805bb92422\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_document\` ADD CONSTRAINT \`FK_7dca5138b462c51ae3f2a217e45\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_inss_benefit\` ADD CONSTRAINT \`FK_8188700956064af6338ecf974f9\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temp_incapacity_benefit_rejection_insured_status_document\` ADD CONSTRAINT \`FK_a9ae561fa235f8608f037e2743a\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_insured_status_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_insured_status\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_insured_status\` ADD CONSTRAINT \`FK_46765c3cd47977173693c4f3fa9\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temp_incapacity_benefit_rejection_work_periods_earnings_history\` ADD CONSTRAINT \`FK_8d024a755cdfc35f4af6239f2cc\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_work_periods_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_work_periods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_work_periods\` ADD CONSTRAINT \`FK_6013f9817945eb0e4b6c7c7878d\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection\` ADD CONSTRAINT \`FK_18f678ea101ff58294df2071e0c\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_result_id\`) REFERENCES \`temporary_incapacity_benefit_rejection_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_de48ccd1c2a2087b6f247f298d0\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_f0b4ad9f4cd67248599cf1ce0cd\` FOREIGN KEY (\`special_category_retirement_analysis_id\`) REFERENCES \`special_category_retirement_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_24e94d519449ff2d50b345e77b1\` FOREIGN KEY (\`rural_or_hybrid_retirement_rejection_id\`) REFERENCES \`rural_or_hybrid_retirement_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_a11ef687a9c70fdd9d958e29426\` FOREIGN KEY (\`disability_retirement_planning_id\`) REFERENCES \`disability_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_5ba08a6a6b94463435e2e8869a1\` FOREIGN KEY (\`disability_retirement_planning_grant_id\`) REFERENCES \`disability_retirement_planning_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_67bfa44ad73608fb045b37f8733\` FOREIGN KEY (\`death_benefit_grant_id\`) REFERENCES \`death_benefit_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_78ea3849a680ec7aca5f92912ef\` FOREIGN KEY (\`death_benefit_rejection_id\`) REFERENCES \`death_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_52d3272e33512e5f53d9c5d575c\` FOREIGN KEY (\`temporary_disability_benefits_grant_id\`) REFERENCES \`temporary_disability_benefits_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_b70934626fbcea894d23d072b83\` FOREIGN KEY (\`accident_benefit_rejection_id\`) REFERENCES \`accident_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_d1ca0140d8785f268c506bd8f84\` FOREIGN KEY (\`general_urban_retirement_grant_id\`) REFERENCES \`general_urban_retirement_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_cdb9ee6d20c2c9321c1af765fe0\` FOREIGN KEY (\`general_urban_retirement_analysis_id\`) REFERENCES \`general_urban_retirement_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_5f48f3d21da2326dc3084bcd765\` FOREIGN KEY (\`general_urban_retirement_denial_id\`) REFERENCES \`general_urban_retirement_denial\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_161119c21d96483f5d6d79e9c72\` FOREIGN KEY (\`disability_retirement_planning_rejection_id\`) REFERENCES \`disability_retirement_planning_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_d839be03e3ce21bd911d1add88e\` FOREIGN KEY (\`bpc_disability_denial_id\`) REFERENCES \`bpc_disability_denial\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_e2c6a1756f9f902c900f67cadae\` FOREIGN KEY (\`temporary_incapacity_benefit_rejection_id\`) REFERENCES \`temporary_incapacity_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_237a38463dd4b4d4fed8db1f6f6\` FOREIGN KEY (\`maternity_pay_grant_id\`) REFERENCES \`maternity_pay_grant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_event\` ADD CONSTRAINT \`FK_3e54f691f2bef6ced5a88955573\` FOREIGN KEY (\`cid_ten_id\`) REFERENCES \`cid_ten\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_event\` ADD CONSTRAINT \`FK_8cf4abea2088699a74173e4243d\` FOREIGN KEY (\`accident_benefit_rejection_id\`) REFERENCES \`accident_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_inss_benefit\` ADD CONSTRAINT \`FK_3f7fe1c88d884659d7fe924b934\` FOREIGN KEY (\`accident_benefit_rejection_id\`) REFERENCES \`accident_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_work_period_document\` ADD CONSTRAINT \`FK_c3cddfb8b813c8a98f717eddc92\` FOREIGN KEY (\`accident_benefit_rejection_work_period_id\`) REFERENCES \`accident_benefit_rejection_work_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_work_period_earnings_history\` ADD CONSTRAINT \`FK_172c195a4c8bb86a7db4207c48b\` FOREIGN KEY (\`accident_benefit_rejection_work_period_id\`) REFERENCES \`accident_benefit_rejection_work_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_work_period\` ADD CONSTRAINT \`FK_e3ab1fbbd183054a827e35f835d\` FOREIGN KEY (\`accident_benefit_rejection_id\`) REFERENCES \`accident_benefit_rejection\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection\` ADD CONSTRAINT \`FK_12e07507cf77f8e6d72b7b63715\` FOREIGN KEY (\`accident_benefit_rejection_result_id\`) REFERENCES \`accident_benefit_rejection_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`affiliate_customer_payment_plan\` ADD CONSTRAINT \`FK_2ab4573af98d7e827bf6213b2b8\` FOREIGN KEY (\`affiliate_customer_id\`) REFERENCES \`affiliate_customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`affiliate_customer_payment_plan\` ADD CONSTRAINT \`FK_b811bd3446d4db48dad7026edd5\` FOREIGN KEY (\`payment_plan_id\`) REFERENCES \`payment_plan\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`affiliate_customer\` ADD CONSTRAINT \`FK_cdcadabf9ba0c6d88a8c42919da\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_payment_plan_affiliate_commission\` ADD CONSTRAINT \`FK_ae60525ed1774c20a42f4f2f605\` FOREIGN KEY (\`organization_payment_plan_id\`) REFERENCES \`organization_payment_plan\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_payment_plan_affiliate_commission\` ADD CONSTRAINT \`FK_f51031e36f0605a286112196270\` FOREIGN KEY (\`affiliate_customer_id\`) REFERENCES \`affiliate_customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`affiliate_bank_transfer\` ADD CONSTRAINT \`FK_3fb985a8187f6c57d5934efb2d4\` FOREIGN KEY (\`affiliate_plan_commission_id\`) REFERENCES \`organization_payment_plan_affiliate_commission\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`affiliate_bank_transfer\` ADD CONSTRAINT \`FK_6082612e99aa862778466d32240\` FOREIGN KEY (\`bank_payment_id\`) REFERENCES \`bank_payment\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`affiliate_bank_transfer\` ADD CONSTRAINT \`FK_94e55182e874bc01e53e28802aa\` FOREIGN KEY (\`bank_transfer_id\`) REFERENCES \`bank_transfer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mini_advisor_result\` ADD CONSTRAINT \`FK_7f01efa1a258c732ceaea0411e8\` FOREIGN KEY (\`mini_advisor_id\`) REFERENCES \`mini_advisor\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mini_advisor\` ADD CONSTRAINT \`FK_fea0a11952be84335fd11f985ee\` FOREIGN KEY (\`mini_advisor_result_id\`) REFERENCES \`mini_advisor_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mini_advisor\` ADD CONSTRAINT \`FK_c4e818f423b649caa08ee369d67\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`organization_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mini_advisor\` ADD CONSTRAINT \`FK_0e3d6aa12714170d67742627e08\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`organization_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_customization\` ADD CONSTRAINT \`FK_3eea7102eb4cb4ab6760639ba14\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_customization\` ADD CONSTRAINT \`FK_212ab4b919e3768f0e7901a8baa\` FOREIGN KEY (\`organization_customization_document_header_template_id\`) REFERENCES \`organization_customization_document_header_template\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_customization\` ADD CONSTRAINT \`FK_d42985ae3fc301782b3ce59a35e\` FOREIGN KEY (\`organization_customization_document_footer_template_id\`) REFERENCES \`organization_customization_document_footer_template\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`regulatory_update_main_change\` ADD CONSTRAINT \`FK_97767b8764de4637860e9e5ae63\` FOREIGN KEY (\`regulatory_update_id\`) REFERENCES \`regulatory_update\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`regulatory_update_email_preference\` ADD CONSTRAINT \`FK_17b18be46727c736d811578757e\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`system_activities\` ADD CONSTRAINT \`FK_0776c71822610268a496c6aa97f\` FOREIGN KEY (\`organization_member_id\`) REFERENCES \`organization_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`system_activities\` ADD CONSTRAINT \`FK_5479b7995c855c2fbda876abaf4\` FOREIGN KEY (\`analysis_tool_client_id\`) REFERENCES \`analysis_tool_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`system_activities\` ADD CONSTRAINT \`FK_07f78e1097a36a30ed392c63433\` FOREIGN KEY (\`analysis_tool_record_id\`) REFERENCES \`analysis_tool_record\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_email_sent\` ADD CONSTRAINT \`FK_56e0785dbf491218d3bd1884e0e\` FOREIGN KEY (\`sent_by_id\`) REFERENCES \`organization_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_email_sent_attachment\` ADD CONSTRAINT \`FK_300809a30a4494b6ac4a46cf40b\` FOREIGN KEY (\`customer_email_sent_id\`) REFERENCES \`customer_email_sent\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_email_sent_attachment\` ADD CONSTRAINT \`FK_b05f74cf323366c306bf22265a9\` FOREIGN KEY (\`analysis_tool_record_id\`) REFERENCES \`analysis_tool_record\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_template\` ADD CONSTRAINT \`FK_68ab5117677e3cb496f1ca5ff63\` FOREIGN KEY (\`owner_id\`) REFERENCES \`organization_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`email_template\` DROP FOREIGN KEY \`FK_68ab5117677e3cb496f1ca5ff63\``);
        await queryRunner.query(`ALTER TABLE \`customer_email_sent_attachment\` DROP FOREIGN KEY \`FK_b05f74cf323366c306bf22265a9\``);
        await queryRunner.query(`ALTER TABLE \`customer_email_sent_attachment\` DROP FOREIGN KEY \`FK_300809a30a4494b6ac4a46cf40b\``);
        await queryRunner.query(`ALTER TABLE \`customer_email_sent\` DROP FOREIGN KEY \`FK_56e0785dbf491218d3bd1884e0e\``);
        await queryRunner.query(`ALTER TABLE \`system_activities\` DROP FOREIGN KEY \`FK_07f78e1097a36a30ed392c63433\``);
        await queryRunner.query(`ALTER TABLE \`system_activities\` DROP FOREIGN KEY \`FK_5479b7995c855c2fbda876abaf4\``);
        await queryRunner.query(`ALTER TABLE \`system_activities\` DROP FOREIGN KEY \`FK_0776c71822610268a496c6aa97f\``);
        await queryRunner.query(`ALTER TABLE \`regulatory_update_email_preference\` DROP FOREIGN KEY \`FK_17b18be46727c736d811578757e\``);
        await queryRunner.query(`ALTER TABLE \`regulatory_update_main_change\` DROP FOREIGN KEY \`FK_97767b8764de4637860e9e5ae63\``);
        await queryRunner.query(`ALTER TABLE \`organization_customization\` DROP FOREIGN KEY \`FK_d42985ae3fc301782b3ce59a35e\``);
        await queryRunner.query(`ALTER TABLE \`organization_customization\` DROP FOREIGN KEY \`FK_212ab4b919e3768f0e7901a8baa\``);
        await queryRunner.query(`ALTER TABLE \`organization_customization\` DROP FOREIGN KEY \`FK_3eea7102eb4cb4ab6760639ba14\``);
        await queryRunner.query(`ALTER TABLE \`mini_advisor\` DROP FOREIGN KEY \`FK_0e3d6aa12714170d67742627e08\``);
        await queryRunner.query(`ALTER TABLE \`mini_advisor\` DROP FOREIGN KEY \`FK_c4e818f423b649caa08ee369d67\``);
        await queryRunner.query(`ALTER TABLE \`mini_advisor\` DROP FOREIGN KEY \`FK_fea0a11952be84335fd11f985ee\``);
        await queryRunner.query(`ALTER TABLE \`mini_advisor_result\` DROP FOREIGN KEY \`FK_7f01efa1a258c732ceaea0411e8\``);
        await queryRunner.query(`ALTER TABLE \`affiliate_bank_transfer\` DROP FOREIGN KEY \`FK_94e55182e874bc01e53e28802aa\``);
        await queryRunner.query(`ALTER TABLE \`affiliate_bank_transfer\` DROP FOREIGN KEY \`FK_6082612e99aa862778466d32240\``);
        await queryRunner.query(`ALTER TABLE \`affiliate_bank_transfer\` DROP FOREIGN KEY \`FK_3fb985a8187f6c57d5934efb2d4\``);
        await queryRunner.query(`ALTER TABLE \`organization_payment_plan_affiliate_commission\` DROP FOREIGN KEY \`FK_f51031e36f0605a286112196270\``);
        await queryRunner.query(`ALTER TABLE \`organization_payment_plan_affiliate_commission\` DROP FOREIGN KEY \`FK_ae60525ed1774c20a42f4f2f605\``);
        await queryRunner.query(`ALTER TABLE \`affiliate_customer\` DROP FOREIGN KEY \`FK_cdcadabf9ba0c6d88a8c42919da\``);
        await queryRunner.query(`ALTER TABLE \`affiliate_customer_payment_plan\` DROP FOREIGN KEY \`FK_b811bd3446d4db48dad7026edd5\``);
        await queryRunner.query(`ALTER TABLE \`affiliate_customer_payment_plan\` DROP FOREIGN KEY \`FK_2ab4573af98d7e827bf6213b2b8\``);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection\` DROP FOREIGN KEY \`FK_12e07507cf77f8e6d72b7b63715\``);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_work_period\` DROP FOREIGN KEY \`FK_e3ab1fbbd183054a827e35f835d\``);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_work_period_earnings_history\` DROP FOREIGN KEY \`FK_172c195a4c8bb86a7db4207c48b\``);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_work_period_document\` DROP FOREIGN KEY \`FK_c3cddfb8b813c8a98f717eddc92\``);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_inss_benefit\` DROP FOREIGN KEY \`FK_3f7fe1c88d884659d7fe924b934\``);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_event\` DROP FOREIGN KEY \`FK_8cf4abea2088699a74173e4243d\``);
        await queryRunner.query(`ALTER TABLE \`accident_benefit_rejection_event\` DROP FOREIGN KEY \`FK_3e54f691f2bef6ced5a88955573\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_237a38463dd4b4d4fed8db1f6f6\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_e2c6a1756f9f902c900f67cadae\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_d839be03e3ce21bd911d1add88e\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_161119c21d96483f5d6d79e9c72\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_5f48f3d21da2326dc3084bcd765\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_cdb9ee6d20c2c9321c1af765fe0\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_d1ca0140d8785f268c506bd8f84\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_b70934626fbcea894d23d072b83\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_52d3272e33512e5f53d9c5d575c\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_78ea3849a680ec7aca5f92912ef\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_67bfa44ad73608fb045b37f8733\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_5ba08a6a6b94463435e2e8869a1\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_a11ef687a9c70fdd9d958e29426\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_24e94d519449ff2d50b345e77b1\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_f0b4ad9f4cd67248599cf1ce0cd\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_de48ccd1c2a2087b6f247f298d0\``);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection\` DROP FOREIGN KEY \`FK_18f678ea101ff58294df2071e0c\``);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_work_periods\` DROP FOREIGN KEY \`FK_6013f9817945eb0e4b6c7c7878d\``);
        await queryRunner.query(`ALTER TABLE \`temp_incapacity_benefit_rejection_work_periods_earnings_history\` DROP FOREIGN KEY \`FK_8d024a755cdfc35f4af6239f2cc\``);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_insured_status\` DROP FOREIGN KEY \`FK_46765c3cd47977173693c4f3fa9\``);
        await queryRunner.query(`ALTER TABLE \`temp_incapacity_benefit_rejection_insured_status_document\` DROP FOREIGN KEY \`FK_a9ae561fa235f8608f037e2743a\``);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_inss_benefit\` DROP FOREIGN KEY \`FK_8188700956064af6338ecf974f9\``);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_document\` DROP FOREIGN KEY \`FK_7dca5138b462c51ae3f2a217e45\``);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_disability_analysis\` DROP FOREIGN KEY \`FK_2edec45b0b1f35c03805bb92422\``);
        await queryRunner.query(`ALTER TABLE \`temp_incapacity_benefit_rejection_disability_analysis_doc\` DROP FOREIGN KEY \`FK_6cb96d0a7cff7ff205192fcb51e\``);
        await queryRunner.query(`ALTER TABLE \`temporary_incapacity_benefit_rejection_disability_analysis_cid\` DROP FOREIGN KEY \`FK_40e5be3953da2de601571052fee\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant\` DROP FOREIGN KEY \`FK_0dbf09f864fc1d0b259a49b4719\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_work_periods\` DROP FOREIGN KEY \`FK_d95c3786cfb90925d20ea9ced9e\``);
        await queryRunner.query(`ALTER TABLE \`temp_disability_benefits_grant_work_periods_earnings_history\` DROP FOREIGN KEY \`FK_fc84df6ddcd859b5de1e40c6764\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_period\` DROP FOREIGN KEY \`FK_8bd86f9501c9b24ef12a64358ee\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_previous_benefits\` DROP FOREIGN KEY \`FK_0a7fc9cd43165a6c11ea78a2238\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_previous_benefits_document\` DROP FOREIGN KEY \`FK_5bb5c3c3dc8f739464f9fe89ca7\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_period_document\` DROP FOREIGN KEY \`FK_8d2c787f5a504f048ba926b77c2\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_legal_proceeding\` DROP FOREIGN KEY \`FK_208b10b09994762bbcac8c3ecc9\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_insured_status\` DROP FOREIGN KEY \`FK_db51dcb6dee04079503bb287f76\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_insured_status_document\` DROP FOREIGN KEY \`FK_9cbb85fc671daa41b718f340c8b\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_inss_benefit\` DROP FOREIGN KEY \`FK_24105a0e93c717b9300265c37a2\``);
        await queryRunner.query(`ALTER TABLE \`temporary_disability_benefits_grant_document\` DROP FOREIGN KEY \`FK_d495fdd8d01ad24f54fdbe5f2d9\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning\` DROP FOREIGN KEY \`FK_5490dafb2d15ebb5d70278f6906\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_remuneration\` DROP FOREIGN KEY \`FK_d50a70e85425e4136767cf47bb4\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period\` DROP FOREIGN KEY \`FK_dda5b7c7d2034d4c63a53d748c6\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period_item\` DROP FOREIGN KEY \`FK_1d4aa88a09fcc00b5195c805f9f\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period_item_document\` DROP FOREIGN KEY \`FK_f390dcfeaecee81c424c6c858e0\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_legal_proceeding\` DROP FOREIGN KEY \`FK_b99de22ec91a8eb020729508a10\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_inss_benefit\` DROP FOREIGN KEY \`FK_c3334211119f55686f6c82f4467\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_document\` DROP FOREIGN KEY \`FK_5a7ef6d0bc6405f3e1862a59cc6\``);
        await queryRunner.query(`ALTER TABLE \`spa_result\` DROP FOREIGN KEY \`FK_9059fa1c6af64371b60a843836c\``);
        await queryRunner.query(`ALTER TABLE \`spa_result_retirement_rule\` DROP FOREIGN KEY \`FK_94122a13d4667f694982b80a2bf\``);
        await queryRunner.query(`ALTER TABLE \`spa_result_dependent_pension_analysis\` DROP FOREIGN KEY \`FK_f18b17030c3bb40c859f7248b0e\``);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_work_history\` DROP FOREIGN KEY \`FK_15d388f0d60f9d5bd1db4257754\``);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_work_history_period\` DROP FOREIGN KEY \`FK_3a0c48a3fddccd6f523887b466e\``);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_work_history_period_document\` DROP FOREIGN KEY \`FK_8901176f40704205180a0410a55\``);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_benefit_dependents\` DROP FOREIGN KEY \`FK_3372c8549c0a75f2dc5726ebb65\``);
        await queryRunner.query(`ALTER TABLE \`spa_deceased_benefit_dependents_document\` DROP FOREIGN KEY \`FK_358c75ce90dec5fc870dbc4cca8\``);
        await queryRunner.query(`ALTER TABLE \`spa_customer_profile_identification\` DROP FOREIGN KEY \`FK_27e61c7381b787e99c3138290e8\``);
        await queryRunner.query(`ALTER TABLE \`spa_customer_profile_identification_document\` DROP FOREIGN KEY \`FK_40531007bc2fb0c2d65efa48f3b\``);
        await queryRunner.query(`ALTER TABLE \`spa_benefit_originator_identification\` DROP FOREIGN KEY \`FK_96690f1ed7525214faa3c3d1bf6\``);
        await queryRunner.query(`ALTER TABLE \`spa_benefit_originator_identification_document\` DROP FOREIGN KEY \`FK_786ce267551df8e4b6640da52f6\``);
        await queryRunner.query(`ALTER TABLE \`special_retirement_grant_period_observation\` DROP FOREIGN KEY \`FK_0567ebe9261dad30405d907e112\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection\` DROP FOREIGN KEY \`FK_9adce3a8ca303c6aa9f56ed21a4\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_work_period\` DROP FOREIGN KEY \`FK_f06f95ab147865f33a78d59f882\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_work_period_earnings_hist\` DROP FOREIGN KEY \`FK_5a097bd29587cfab937318c4a0d\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_work_period_document\` DROP FOREIGN KEY \`FK_7e0c17305ae532de862d6b2fd0d\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_work_period_doc_analysis\` DROP FOREIGN KEY \`FK_303558499eb1025e42af3f6ea66\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_time_accelerator\` DROP FOREIGN KEY \`FK_f21e8903bf2d3c66872391e1353\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_testimonial_witness\` DROP FOREIGN KEY \`FK_bf0db2c5dafafae97fac551d4c8\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_testimonial_witness_doc\` DROP FOREIGN KEY \`FK_35be67c51a0264c680bb74e9994\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_period\` DROP FOREIGN KEY \`FK_7514e542f6eb2ef456d33151e86\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_period_member\` DROP FOREIGN KEY \`FK_3ed7eba9022a2f10ddd2296dc33\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_period_member_document\` DROP FOREIGN KEY \`FK_b71d2e04f813a6444a51de3f973\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_period_document\` DROP FOREIGN KEY \`FK_0e85e09ec4376dfc7a1b213ba3b\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_legal_proceeding\` DROP FOREIGN KEY \`FK_651e03f0fd195c3ea03c8f3abb6\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_inss_benefit\` DROP FOREIGN KEY \`FK_de881f54db61539e8d3cd0992fa\``);
        await queryRunner.query(`ALTER TABLE \`rural_or_hybrid_retirement_rejection_document\` DROP FOREIGN KEY \`FK_b9776cb99104d90b1d6386556df\``);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant\` DROP FOREIGN KEY \`FK_aa52d2c2319dfd0c8d690b1291e\``);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_legal_proceeding\` DROP FOREIGN KEY \`FK_b1c2a28a03d2a672175a4b81671\``);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_inss_benefit\` DROP FOREIGN KEY \`FK_6f7c30501af6ebfe45089c3f4fc\``);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_earnings_history\` DROP FOREIGN KEY \`FK_736f2889e8b20d7578ce1bb98fc\``);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_earnings_history\` DROP FOREIGN KEY \`FK_7e27529be9de63c2a096629d8f4\``);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_period\` DROP FOREIGN KEY \`FK_95bb8ac7b999ddc0aa9fd4e2cd0\``);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_period_document\` DROP FOREIGN KEY \`FK_4cb8f08b65f08b851da32327950\``);
        await queryRunner.query(`ALTER TABLE \`maternity_pay_grant_document\` DROP FOREIGN KEY \`FK_9956520cfbc84b2291cf0e6d461\``);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial\` DROP FOREIGN KEY \`FK_0f64511146e3bab49f0704c1ce6\``);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_time_accelerator\` DROP FOREIGN KEY \`FK_7517c3fc64dbe662f139a9b7c8a\``);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_period\` DROP FOREIGN KEY \`FK_dd3f0d902061c919eae421420b0\``);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_period_earnings_history\` DROP FOREIGN KEY \`FK_317128228030c9ae014697dace6\``);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_period_document\` DROP FOREIGN KEY \`FK_732df9bb577c2cd68663ce238e8\``);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_inss_benefit\` DROP FOREIGN KEY \`FK_e4eeb546aacceda46a689d5d0f0\``);
        await queryRunner.query(`ALTER TABLE \`general_urban_retirement_denial_document\` DROP FOREIGN KEY \`FK_2a3acf315c56d30ababa417dc71\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning\` DROP FOREIGN KEY \`FK_b111c1afd93ea457abc5f7b8518\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_result\` DROP FOREIGN KEY \`FK_e2a966ef33036855d12187034cb\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_remuneration\` DROP FOREIGN KEY \`FK_68d222b182c48f73000090c6a63\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period\` DROP FOREIGN KEY \`FK_52a6d25e0f0f5c9483e9a3874bb\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_special_time\` DROP FOREIGN KEY \`FK_eae8f709d84f24cf350ab87d6a0\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_special_time_document\` DROP FOREIGN KEY \`FK_f5ee414426e28fa5b1a2c2ffa1b\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_disability\` DROP FOREIGN KEY \`FK_b205ea894cca82a9cd61b9ae332\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_disability\` DROP FOREIGN KEY \`FK_d545cc333ea61dd1ce9a5af4a76\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_period_disability_document\` DROP FOREIGN KEY \`FK_3963237e6f03ccd2fa598e40302\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_legal_proceeding\` DROP FOREIGN KEY \`FK_93d315a1e03faee4ead93c642e6\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_inss_benefit\` DROP FOREIGN KEY \`FK_c54e0d73ea5eee010607750f2f6\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_document\` DROP FOREIGN KEY \`FK_25ff45060081bc1f21612162545\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection\` DROP FOREIGN KEY \`FK_f4473c093f619f933d389e0c27a\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_time_accelerator\` DROP FOREIGN KEY \`FK_8dd2b57e0b2b392adff47cc1097\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_period\` DROP FOREIGN KEY \`FK_b45477ee3545060de55178a853c\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_period_earnings_history\` DROP FOREIGN KEY \`FK_fd364b657fc89dbc8fada328faa\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_period_document\` DROP FOREIGN KEY \`FK_4b8036052952e2fcae56cd6dc52\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_inss_benefit\` DROP FOREIGN KEY \`FK_d45a5e41daa6c2039df8c7aae71\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_rejection_document\` DROP FOREIGN KEY \`FK_cfd8d7ee91314485f036e022f93\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant\` DROP FOREIGN KEY \`FK_e01eb46945d56b38e24ab445a00\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_time_accelerator\` DROP FOREIGN KEY \`FK_d7aa70164713ebce108a0772957\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_period\` DROP FOREIGN KEY \`FK_8b0953dce38e733aad3c2b279f5\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_period_earnings_history\` DROP FOREIGN KEY \`FK_7cec18c7b75a792b7ef48219c72\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_period_document\` DROP FOREIGN KEY \`FK_01286dee51034a4d9ca36d554d8\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_legal_proceeding\` DROP FOREIGN KEY \`FK_7d2a31f4f32b81929ca92e57841\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_inss_benefit\` DROP FOREIGN KEY \`FK_1b6b36f2a052c9c39fb2070c542\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_document\` DROP FOREIGN KEY \`FK_0d09c38b950a5d9375bc0e56ff7\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_disability_period\` DROP FOREIGN KEY \`FK_f4eeb9568b97846552caa7daa2b\``);
        await queryRunner.query(`ALTER TABLE \`disability_retirement_planning_grant_disability_period_document\` DROP FOREIGN KEY \`FK_a17c85655354f8fc894cdc428e6\``);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection\` DROP FOREIGN KEY \`FK_b5ab738cfd5f6f3dbfeda05866a\``);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_time_accelerator\` DROP FOREIGN KEY \`FK_cb8631b016f91dd23dfc9b708b6\``);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_period_document\` DROP FOREIGN KEY \`FK_b5f448c6fe6fd536fe79810ffbc\``);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_period\` DROP FOREIGN KEY \`FK_941ec829e4900ede71b3541794b\``);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_period_earnings_history\` DROP FOREIGN KEY \`FK_f03f2a6d1751e879a38760934cb\``);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_legal_representative\` DROP FOREIGN KEY \`FK_6f01cefbbb65db41c984ea69748\``);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_legal_proceeding\` DROP FOREIGN KEY \`FK_ff5bedc3bc8d85de8d1520574c4\``);
        await queryRunner.query(`ALTER TABLE \`death_benefit_rejection_institutor\` DROP FOREIGN KEY \`FK_b63271a1053b7195bc52d735060\``);
        await queryRunner.query(`ALTER TABLE \`accident_assistance_terminated\` DROP COLUMN \`inss_benefit_number\``);
        await queryRunner.query(`CREATE INDEX \`FK_email_template_owner\` ON \`email_template\` (\`owner_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_customer_email_sent_attachment_customer_email_sent\` ON \`customer_email_sent_attachment\` (\`customer_email_sent_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_customer_email_sent_attachment_analysis_tool_record\` ON \`customer_email_sent_attachment\` (\`analysis_tool_record_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_364942f94d78d35288f43ece6d7\` ON \`customer_email_sent\` (\`sent_by_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_acc_config\` ON \`affiliate_customer_config\` (\`config\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_system_activities_organization_member\` ON \`system_activities\` (\`organization_member_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_system_activities_analysis_tool_record\` ON \`system_activities\` (\`analysis_tool_record_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_system_activities_analysis_tool_client\` ON \`system_activities\` (\`analysis_tool_client_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_rtccp_adjustment_period\` ON \`rural_timeline_cnis_contribution_period_adjustment\` (\`rural_timeline_cnis_contribution_period_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_org_customization_organization\` ON \`organization_customization\` (\`organization_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_org_customization_header_template\` ON \`organization_customization\` (\`organization_customization_document_header_template_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_org_customization_footer_template\` ON \`organization_customization\` (\`organization_customization_document_footer_template_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_abt_bank_payment\` ON \`affiliate_bank_transfer\` (\`bank_payment_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_abt_commission\` ON \`affiliate_bank_transfer\` (\`affiliate_plan_commission_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_abt_bank_transfer\` ON \`affiliate_bank_transfer\` (\`bank_transfer_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_opp_affiliate_commission_plan\` ON \`organization_payment_plan_affiliate_commission\` (\`organization_payment_plan_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_opp_affiliate_commission_affiliate\` ON \`organization_payment_plan_affiliate_commission\` (\`affiliate_customer_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_affiliate_customer_customer_id\` ON \`affiliate_customer\` (\`customer_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_affiliate_customer_payment_plan_payment_plan_id\` ON \`affiliate_customer_payment_plan\` (\`payment_plan_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_affiliate_customer_payment_plan_affiliate_customer_id\` ON \`affiliate_customer_payment_plan\` (\`affiliate_customer_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`bank_external_id\` ON \`bank_transfer\` (\`bank_external_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_de48ccd1c2a2087b6f247f298d\` ON \`analysis_tool_record\` (\`teacher_retirement_planning_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d839be03e3ce21bd911d1add88\` ON \`analysis_tool_record\` (\`bpc_disability_denial_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_cdb9ee6d20c2c9321c1af765fe\` ON \`analysis_tool_record\` (\`general_urban_retirement_analysis_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_a11ef687a9c70fdd9d958e2942\` ON \`analysis_tool_record\` (\`disability_retirement_planning_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_4bf0d6a2aa0890f504095a6986\` ON \`analysis_tool_record\` (\`accident_assistance_terminated_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_467461f25aaf1080665789dfd2\` ON \`analysis_tool_record\` (\`special_retirement_grant_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_2e2cb32e1168368c156782d993\` ON \`analysis_tool_record\` (\`bpc_elderly_analysis_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_d1ca0140d8785f268c506bd8f84\` ON \`analysis_tool_record\` (\`general_urban_retirement_grant_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_analysis_tool_record_to_maternity_pay_grant\` ON \`analysis_tool_record\` (\`maternity_pay_grant_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_40b7c5c5f6f722d303f7866fb10\` ON \`analysis_tool_record\` (\`death_benefit_grant_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_tdbg_to_result\` ON \`temporary_disability_benefits_grant\` (\`temporary_disability_benefits_grant_result_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_0dbf09f864fc1d0b259a49b471\` ON \`temporary_disability_benefits_grant\` (\`temporary_disability_benefits_grant_result_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_c07a04bf5030365523fe0475a7\` ON \`spa_result\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9059fa1c6af64371b60a843836\` ON \`spa_result\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_f44913cb29a2e09a7e37a055607\` ON \`spa_result_retirement_rule\` (\`survivor_pension_analysis_result_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_563c83aa0b7d476ceb7e38f2bcc\` ON \`spa_result_dependent_pension_analysis\` (\`survivor_pension_analysis_result_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_02952d3df1d2f65220433900c6\` ON \`spa_deceased_work_history\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_15d388f0d60f9d5bd1db425775\` ON \`spa_deceased_work_history\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_88e4f2a0e52506a4b818a094384\` ON \`spa_deceased_work_history_period\` (\`deceased_work_history_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_351b571298612eb99f1480abf0a\` ON \`spa_deceased_work_history_period_document\` (\`deceased_work_history_period_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_a68932b69afdb1df547c3959637\` ON \`spa_deceased_benefit_dependents\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_fe13f7fc78a045ab3ba03df35db\` ON \`spa_deceased_benefit_dependents_document\` (\`deceased_benefit_dependents_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_e5d13c0b0ff4fc0aac9c0bd3f1\` ON \`spa_customer_profile_identification\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_27e61c7381b787e99c3138290e\` ON \`spa_customer_profile_identification\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_5a40eca4f2b9a31b502dadc419a\` ON \`spa_customer_profile_identification_document\` (\`customer_profile_identification_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_1f9bbd7929d29a60fa18efbfa7\` ON \`spa_benefit_originator_identification\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_96690f1ed7525214faa3c3d1bf\` ON \`spa_benefit_originator_identification\` (\`survivor_pension_analysis_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_c9430f87a08b094fde62807d974\` ON \`spa_benefit_originator_identification_document\` (\`benefit_originator_identification_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_special_retirement_grant_period_observation_period\` ON \`special_retirement_grant_period_observation\` (\`special_retirement_grant_period_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_overdue_contribution_cnis_contribution_period\` ON \`rural_timeline_cnis_contribution_period_overdue_contribution\` (\`rural_timeline_cnis_contribution_period_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_cnis_contribution_period_document_period\` ON \`rural_timeline_cnis_contribution_period_document\` (\`rural_timeline_cnis_contribution_period_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_pending_exit_date_cnis_contribution_period\` ON \`rural_timeline_period_pending_exit_date\` (\`rural_timeline_cnis_contribution_period_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_aa52d2c2319dfd0c8d690b1291\` ON \`maternity_pay_grant\` (\`maternity_pay_grant_result_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_maternity_pay_grant_legal_proceeding_to_grant\` ON \`maternity_pay_grant_legal_proceeding\` (\`maternity_pay_grant_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_maternity_pay_grant_inss_benefit_to_grant\` ON \`maternity_pay_grant_inss_benefit\` (\`maternity_pay_grant_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_maternity_pay_grant_earnings_history_to_period\` ON \`maternity_pay_grant_earnings_history\` (\`maternity_pay_grant_period_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_maternity_pay_grant_earnings_history_to_grant\` ON \`maternity_pay_grant_earnings_history\` (\`maternity_pay_grant_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_maternity_pay_grant_period_to_grant\` ON \`maternity_pay_grant_period\` (\`maternity_pay_grant_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_maternity_pay_grant_period_document_to_period\` ON \`maternity_pay_grant_period_document\` (\`maternity_pay_grant_period_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_maternity_pay_grant_document_to_grant\` ON \`maternity_pay_grant_document\` (\`maternity_pay_grant_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_death_benefit_grant_time_accelerator_death_benefit_grant\` ON \`death_benefit_grant_time_accelerator\` (\`death_benefit_grant_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_6acdbf254bed5eb62d4d54958d3\` ON \`death_benefit_grant_document\` (\`death_benefit_grant_institutor_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_cfbbaafae7a8df980f0f21a2a3\` ON \`auth_identity\` (\`support_attendant_id\`)`);
    }

}
