import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddRpdrTypeToAnalysisToolRecord20260508000000 implements MigrationInterface {
  public readonly name = 'AddRpdrTypeToAnalysisToolRecord20260508000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` CHANGE \`type\` \`type\` enum('analise_rapida_cnis', 'planejamento_previdenciario_rgps', 'planejamento_aposentadoria_rpps', 'planejamento_previdenciario_professor', 'atividade_especial', 'analise_caso_judicial', 'analise_procedimento_administrativo_inss', 'gerador_perguntas_medicas', 'analise_geradora_objeção_laudo_medico_social', 'gerador_discurso', 'avaliacao_deficiencia_para_bpc', 'analise_renda_per_capita_para_bpc', 'analise_linha_tempo_rural', 'gerador_perguntas_audiencia', 'analise_qualidade_segurado', 'planejamento_aposentadoria_para_deficiente', 'concessao_aposentadoria_urbana_geral', 'analise_aposentadoria_urbana_geral', 'aposentadoria_categoria_especial', 'concessao_aposentadoria_especial', 'indeferimento_aposentadoria_especial', 'concessao_aposentadoria_para_deficiente', 'concessao_pensao_por_morte', 'indeferimento_pensao_por_morte', 'auxilio_incapacidade_temporaria', 'indeferimento_aposentadoria_rural_hibrida', 'analise_aposentadoria_rural_hibrida', 'pensao_por_morte', 'indeferimento_aposentadoria_urbana_geral', 'revisao_aposentadoria_urbana_geral', 'indeferimento_acidente', 'indeferimento_aposentadoria_para_deficiente', 'indeferimento_bpc_deficiente', 'bpc_ao_idoso', 'indeferimento_salario_maternidade', 'indeferimento_auxilio_incapacidade_temporaria', 'cessacao_auxilio_incapacidade_temporaria', 'cessacao_bpc_idoso', 'concessao_salario_maternidade', 'indeferimento_aposentadoria_professor', 'bpc_deficiente_cessado', 'auxilio_acidente_cessado', 'concessao_auxilio_acidente', 'indeferimento_aposentadoria_incapacidade_permanente') NOT NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`analysis_tool_record\` CHANGE \`type\` \`type\` enum('analise_rapida_cnis', 'planejamento_previdenciario_rgps', 'planejamento_aposentadoria_rpps', 'planejamento_previdenciario_professor', 'atividade_especial', 'analise_caso_judicial', 'analise_procedimento_administrativo_inss', 'gerador_perguntas_medicas', 'analise_geradora_objeção_laudo_medico_social', 'gerador_discurso', 'avaliacao_deficiencia_para_bpc', 'analise_renda_per_capita_para_bpc', 'analise_linha_tempo_rural', 'gerador_perguntas_audiencia', 'analise_qualidade_segurado', 'planejamento_aposentadoria_para_deficiente', 'concessao_aposentadoria_urbana_geral', 'analise_aposentadoria_urbana_geral', 'aposentadoria_categoria_especial', 'concessao_aposentadoria_especial', 'indeferimento_aposentadoria_especial', 'concessao_aposentadoria_para_deficiente', 'concessao_pensao_por_morte', 'indeferimento_pensao_por_morte', 'auxilio_incapacidade_temporaria', 'indeferimento_aposentadoria_rural_hibrida', 'analise_aposentadoria_rural_hibrida', 'pensao_por_morte', 'indeferimento_aposentadoria_urbana_geral', 'revisao_aposentadoria_urbana_geral', 'indeferimento_acidente', 'indeferimento_aposentadoria_para_deficiente', 'indeferimento_bpc_deficiente', 'bpc_ao_idoso', 'indeferimento_salario_maternidade', 'indeferimento_auxilio_incapacidade_temporaria', 'cessacao_auxilio_incapacidade_temporaria', 'cessacao_bpc_idoso', 'concessao_salario_maternidade', 'indeferimento_aposentadoria_professor', 'bpc_deficiente_cessado', 'auxilio_acidente_cessado', 'concessao_auxilio_acidente') NOT NULL`,
    );
  }
}
