export enum AnalysisToolRecordTypeEnum {
  CNIS_FAST_ANALYSIS = 'analise_rapida_cnis',
  RETIREMENT_PLANNING_RGPS = 'planejamento_previdenciario_rgps',
  RETIREMENT_PLANNING_RPPS = 'planejamento_aposentadoria_rpps',
  TEACHER_RETIREMENT_PLANNING = 'planejamento_previdenciario_professor',
  SPECIAL_ACTIVITY = 'atividade_especial',
  JUDICIAL_CASE_ANALYSIS = 'analise_caso_judicial',
  ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS = 'analise_procedimento_administrativo_inss',
  MEDICAL_QUESTION_GENERATOR = 'gerador_perguntas_medicas',
  MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS = 'analise_geradora_objeção_laudo_medico_social',
  SPEECH_GENERATOR = 'gerador_discurso',
  DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS = 'avaliacao_deficiencia_para_bpc',
  PER_CAPITA_INCOME_FOR_BPC_ANALYSIS = 'analise_renda_per_capita_para_bpc',
  RURAL_TIMELINE_ANALYSIS = 'analise_linha_tempo_rural',
  AUDIENCE_QUESTIONS_GENERATOR = 'gerador_perguntas_audiencia',
  INSURANCE_QUALITY_ANALYSIS = 'analise_qualidade_segurado',
  DISABILITY_RETIREMENT_PLANNING = 'planejamento_aposentadoria_para_deficiente',
  GENERAL_URBAN_RETIREMENT_GRANT = 'concessao_aposentadoria_urbana_geral',
  GENERAL_URBAN_RETIREMENT_ANALYSIS = 'analise_aposentadoria_urbana_geral',
  SPECIAL_CATEGORY_RETIREMENT = 'aposentadoria_categoria_especial',
  DISABILITY_RETIREMENT_PLANNING_GRANT = 'concessao_aposentadoria_para_deficiente',
  TEMPORARY_DISABILITY_BENEFITS_GRANT = 'auxilio_incapacidade_temporaria',
}
