export enum TeacherRetirementPlanningRejectionDenialReasonEnum {
  PERIOD_NOT_RECOGNIZED_AS_TEACHER = 'PERIOD_NOT_RECOGNIZED_AS_TEACHER',
  ACTIVITY_NOT_RECOGNIZED_AS_EXCLUSIVE_TEACHING = 'ACTIVITY_NOT_RECOGNIZED_AS_EXCLUSIVE_TEACHING',
  INSUFFICIENT_CONTRIBUTION_TIME = 'INSUFFICIENT_CONTRIBUTION_TIME',
  LACK_OF_SUPPORTING_DOCUMENTATION = 'LACK_OF_SUPPORTING_DOCUMENTATION',
  FAILURE_TO_PROVE_BASIC_EDUCATION_FUNCTION = 'FAILURE_TO_PROVE_BASIC_EDUCATION_FUNCTION',
  OTHER = 'OTHER',
}
