export enum GeneralUrbanRetirementAnalysisBenefitTypeEnum {
  ORIGINAL_ANALYSIS = 'ORIGINAL_ANALYSIS',
  FEDERATIVE_ENTITY_REVIEW = 'FEDERATIVE_ENTITY_REVIEW',
  BENEFIT_GRANTED_REVIEW = 'BENEFIT_GRANTED_REVIEW',
}
