export enum GeneralUrbanRetirementReviewDocumentTypeEnum {
  ADMINISTRATIVE_PROCEDURE = 'ADMINISTRATIVE_PROCEDURE',
  CNIS = 'CNIS',
  CONTRIBUTIVE_PROFILE_SUMMARY = 'CONTRIBUTIVE_PROFILE_SUMMARY',
  OTHER = 'OTHER',
}
