export enum MimeTypeEnum {
  IMAGE_JPEG = 'image/jpeg',
  IMAGE_PNG = 'image/png',
  APPLICATION_PDF = 'application/pdf',
  AUDIO_MPEG = 'audio/mpeg',
  AUDIO_WEBM = 'audio/webm',
  AUDIO_WAV = 'audio/wav',
  AUDIO_X_WAV = 'audio/x-wav',
  AUDIO_WAVE = 'audio/wave',
  AUDIO_VND_WAVE = 'audio/vnd.wave',
  APPLICATION_OCTET_STREAM = 'application/octet-stream',
  VIDEO_WEBM = 'video/webm',
  AUDIO_OGG = 'audio/ogg',
  WORD = 'application/msword',
}
