export enum DeathBenefitRejectionCategoryEnum {
  EMPREGADO_URBANO = 'EMPREGADO_URBANO',
  EMPREGADO_RURAL = 'EMPREGADO_RURAL',
  EMPREGO_DOMESTICO = 'EMPREGO_DOMESTICO',
  TRABALHADOR_AVULSO = 'TRABALHADOR_AVULSO',
  CONTRIBUINTE_INDIVIDUAL_AUTONOMO = 'CONTRIBUINTE_INDIVIDUAL_AUTONOMO',
  CONTRIBUINTE_INDIVIDUAL_PRESTADOR = 'CONTRIBUINTE_INDIVIDUAL_PRESTADOR',
  MEI = 'MEI',
  SEGURADO_ESPECIAL = 'SEGURADO_ESPECIAL',
  SEGURADO_FACULTATIVO = 'SEGURADO_FACULTATIVO',
}
