export enum InterviewFormBenefitTypeEnum {
  AUXILIO_POR_INCAPACIDADE_TEMPORARIA = 'AUXILIO_POR_INCAPACIDADE_TEMPORARIA',
  APOSENTADORIA_POR_INCAPACIDADE_PERMANENTE = 'APOSENTADORIA_POR_INCAPACIDADE_PERMANENTE',
  AUXILIO_ACIDENTE = 'AUXILIO_ACIDENTE',
  SALARIO_MATERNIDADE = 'SALARIO_MATERNIDADE',
  PENSAO_POR_MORTE = 'PENSAO_POR_MORTE',
  APOSENTADORIA_URBANA_COMUM = 'APOSENTADORIA_URBANA_COMUM',
  APOSENTADORIA_RURAL_OU_HIBRIDA = 'APOSENTADORIA_RURAL_OU_HIBRIDA',
  APOSENTADORIA_DA_PESSOA_COM_DEFICIENCIA = 'APOSENTADORIA_DA_PESSOA_COM_DEFICIENCIA',
  APOSENTADORIA_DO_PROFESSOR = 'APOSENTADORIA_DO_PROFESSOR',
  APOSENTADORIA_ESPECIAL = 'APOSENTADORIA_ESPECIAL',
  BPC_IDOSO = 'BPC_IDOSO',
  BPC_DEFICIENTE = 'BPC_DEFICIENTE',
}
