export enum TeacherRetirementPlanningActivityTypeEnum {
  CLASSROOM_ONLY = 'CLASSROOM_ONLY',
  CLASSROOM_AND_PEDAGOGICAL_FUNCTION = 'CLASSROOM_AND_PEDAGOGICAL_FUNCTION',
  NO_TEACHING_ACTIVITY = 'NO_TEACHING_ACTIVITY',
}
