import { MigrationInterface, QueryRunner } from "typeorm";

export class MedicalSocialReportObGeneratorAnalysisTb1769027717636 implements MigrationInterface {
    name = 'MedicalSocialReportObGeneratorAnalysisTb1769027717636'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`ms_report_objection_analysis_benefit\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`inss_benefit_number\` varchar(100) NOT NULL, \`ms_report_objection_analysis_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ms_report_objection_analysis_document\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`document\` varchar(255) NOT NULL, \`type\` enum ('laudo_medico_pericial', 'processo_judicial') NOT NULL, \`ms_report_objection_analysis_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ms_report_objection_analysis_legal_proc\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`legal_proceeding_number\` varchar(100) NOT NULL, \`ms_report_objection_analysis_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ms_report_objection_analysis_result\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`ms_report_objection_complete_analysis\` longtext NULL, \`ms_report_objection_simplified_analysis\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ms_report_objection_analysis\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`ms_report_objection_analysis_result_id\` varchar(36) NULL, \`created_by_id\` varchar(36) NULL, \`updated_by_id\` varchar(36) NULL, UNIQUE INDEX \`REL_aa6fcc2b5efdb4266072a7fa91\` (\`ms_report_objection_analysis_result_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD \`medical_and_social_report_objection_generator_analysis_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD UNIQUE INDEX \`IDX_446c4320686781296fbd94b590\` (\`medical_and_social_report_objection_generator_analysis_id\`)`);
        await queryRunner.query(`ALTER TABLE \`payment_plan_paid_resource\` CHANGE \`resource\` \`resource\` enum ('LEGAL_PLEADING_COMPLETE_ANALYSIS', 'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS', 'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS', 'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS', 'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS', 'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS', 'LEGAL_PROCEEDING_MONITORING', 'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS', 'ELOY_CHAT_LEGISLATION_QUESTIONS', 'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH', 'ELOY_CHAT_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS', 'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS', 'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_COMPLETE_ANALYSIS', 'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_SIMPLIFIED_ANALYSIS') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` CHANGE \`type\` \`type\` enum ('analise_rapida_cnis', 'planejamento_previdenciario_rgps', 'planejamento_aposentadoria_rpps', 'analise_caso_judicial', 'analise_procedimento_administrativo_inss', 'analise_geradora_objeção_laudo_medico_social') NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_446c4320686781296fbd94b590\` ON \`analysis_tool_record\` (\`medical_and_social_report_objection_generator_analysis_id\`)`);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis_benefit\` ADD CONSTRAINT \`FK_f09fd241439be98598dfc86e94f\` FOREIGN KEY (\`ms_report_objection_analysis_id\`) REFERENCES \`ms_report_objection_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis_document\` ADD CONSTRAINT \`FK_d1f4deb7b08eab6de3703cb3e9c\` FOREIGN KEY (\`ms_report_objection_analysis_id\`) REFERENCES \`ms_report_objection_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis_legal_proc\` ADD CONSTRAINT \`FK_fe992596dd0942eed8f83f5867e\` FOREIGN KEY (\`ms_report_objection_analysis_id\`) REFERENCES \`ms_report_objection_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis\` ADD CONSTRAINT \`FK_aa6fcc2b5efdb4266072a7fa915\` FOREIGN KEY (\`ms_report_objection_analysis_result_id\`) REFERENCES \`ms_report_objection_analysis_result\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis\` ADD CONSTRAINT \`FK_f67cbe44d09e381cce002ac6e24\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`organization_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis\` ADD CONSTRAINT \`FK_7d69d4e3d869b8b50088df8b244\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`organization_member\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_446c4320686781296fbd94b5903\` FOREIGN KEY (\`medical_and_social_report_objection_generator_analysis_id\`) REFERENCES \`ms_report_objection_analysis\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_446c4320686781296fbd94b5903\``);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis\` DROP FOREIGN KEY \`FK_7d69d4e3d869b8b50088df8b244\``);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis\` DROP FOREIGN KEY \`FK_f67cbe44d09e381cce002ac6e24\``);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis\` DROP FOREIGN KEY \`FK_aa6fcc2b5efdb4266072a7fa915\``);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis_legal_proc\` DROP FOREIGN KEY \`FK_fe992596dd0942eed8f83f5867e\``);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis_document\` DROP FOREIGN KEY \`FK_d1f4deb7b08eab6de3703cb3e9c\``);
        await queryRunner.query(`ALTER TABLE \`ms_report_objection_analysis_benefit\` DROP FOREIGN KEY \`FK_f09fd241439be98598dfc86e94f\``);
        await queryRunner.query(`DROP INDEX \`REL_446c4320686781296fbd94b590\` ON \`analysis_tool_record\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` CHANGE \`type\` \`type\` enum ('analise_rapida_cnis', 'planejamento_previdenciario_rgps', 'planejamento_aposentadoria_rpps', 'analise_procedimento_administrativo_inss', 'analise_caso_judicial') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_plan_paid_resource\` CHANGE \`resource\` \`resource\` enum ('LEGAL_PLEADING_COMPLETE_ANALYSIS', 'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS', 'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS', 'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS', 'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS', 'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS', 'LEGAL_PROCEEDING_MONITORING', 'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS', 'ELOY_CHAT_LEGISLATION_QUESTIONS', 'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH', 'ELOY_CHAT_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS', 'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP INDEX \`IDX_446c4320686781296fbd94b590\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP COLUMN \`medical_and_social_report_objection_generator_analysis_id\``);
        await queryRunner.query(`DROP INDEX \`REL_aa6fcc2b5efdb4266072a7fa91\` ON \`ms_report_objection_analysis\``);
        await queryRunner.query(`DROP TABLE \`ms_report_objection_analysis\``);
        await queryRunner.query(`DROP TABLE \`ms_report_objection_analysis_result\``);
        await queryRunner.query(`DROP TABLE \`ms_report_objection_analysis_legal_proc\``);
        await queryRunner.query(`DROP TABLE \`ms_report_objection_analysis_document\``);
        await queryRunner.query(`DROP TABLE \`ms_report_objection_analysis_benefit\``);
    }

}
