import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTeacherRetirementPlanningFlow1771872762167 implements MigrationInterface {
    name = 'AddTeacherRetirementPlanningFlow1771872762167'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period_document\` DROP FOREIGN KEY \`FK_cnis_contribution_period_document_period\``);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning_document\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`document\` longtext NOT NULL, \`teacher_retirement_planning_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning_inss_benefit\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`inss_benefit_number\` varchar(100) NOT NULL, \`teacher_retirement_planning_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning_legal_proceeding\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`legal_proceeding_number\` varchar(100) NOT NULL, \`teacher_retirement_planning_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning_period_item_document\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`document\` longtext NOT NULL, \`teacher_retirement_planning_period_item_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning_period_item\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`start_date\` date NOT NULL, \`end_date\` date NOT NULL, \`institution_name\` varchar(255) NOT NULL, \`institution_type\` enum ('PRIVATE', 'PUBLIC') NOT NULL, \`education_level\` enum ('EARLY_CHILDHOOD', 'ELEMENTARY', 'HIGH_SCHOOL') NOT NULL, \`role_performed\` enum ('CLASSROOM', 'PRINCIPAL', 'COORDINATOR') NOT NULL, \`teacher_retirement_planning_period_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning_period\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`start_date\` date NOT NULL, \`end_date\` date NOT NULL, \`position_name\` varchar(255) NOT NULL, \`career_name\` varchar(255) NOT NULL, \`service_type\` enum ('COMMON', 'SPECIAL', 'DISABILITY', 'TEACHER', 'RGPS_CTC') NOT NULL, \`department\` varchar(255) NOT NULL, \`teacher_retirement_planning_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning_remuneration\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`contribution_date\` date NOT NULL, \`amount\` decimal(15,2) NOT NULL, \`teacher_retirement_planning_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning_result\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`teacher_retirement_planning_complete_analysis\` longtext NULL, \`teacher_retirement_planning_simplified_analysis\` longtext NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`teacher_retirement_planning\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`federative_entity\` enum ('STATE', 'MUNICIPALITY', 'UNION', 'FEDERAL_DISTRICT') NOT NULL, \`state\` varchar(2) NULL, \`municipality\` varchar(255) NULL, \`analysis_name\` varchar(255) NULL, \`activity_type\` enum ('CLASSROOM_ONLY', 'CLASSROOM_AND_PEDAGOGICAL_FUNCTION', 'NO_TEACHING_ACTIVITY') NOT NULL, \`public_service_start_date\` date NOT NULL, \`career_start_date\` date NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD \`teacher_retirement_planning_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD UNIQUE INDEX \`IDX_de48ccd1c2a2087b6f247f298d\` (\`teacher_retirement_planning_id\`)`);
        await queryRunner.query(`ALTER TABLE \`payment_plan_paid_resource\` CHANGE \`resource\` \`resource\` enum ('LEGAL_PLEADING_COMPLETE_ANALYSIS', 'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS', 'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS', 'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS', 'TEACHER_RETIREMENT_PLANNING_COMPLETE_ANALYSIS', 'TEACHER_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS', 'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS', 'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS', 'LEGAL_PROCEEDING_MONITORING', 'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS', 'ELOY_CHAT_LEGISLATION_QUESTIONS', 'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH', 'ELOY_CHAT_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS', 'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS', 'SPECIAL_ACTIVITY_COMPLETE_ANALYSIS', 'SPECIAL_ACTIVITY_SIMPLIFIED_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS', 'MEDICAL_QUESTION_GENERATOR_SIMPLIFIED_ANALYSIS', 'MEDICAL_QUESTION_GENERATOR_COMPLETE_ANALYSIS', 'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_COMPLETE_ANALYSIS', 'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_SIMPLIFIED_ANALYSIS', 'SPEECH_GENERATOR_COMPLETE_ANALYSIS', 'SPEECH_GENERATOR_SIMPLIFIED_ANALYSIS', 'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS', 'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS', 'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS', 'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS', 'INSURANCE_QUALITY_ANALYSIS_COMPLETE_ANALYSIS', 'INSURANCE_QUALITY_ANALYSIS_SIMPLIFIED_ANALYSIS', 'INITIAL_PETITION_GENERATOR_COMPLETE_ANALYSIS', 'INITIAL_PETITION_GENERATOR_SIMPLIFIED_ANALYSIS', 'ADMINISTRATIVE_REQUEST_GENERATOR_COMPLETE_ANALYSIS', 'ADMINISTRATIVE_REQUEST_GENERATOR_SIMPLIFIED_ANALYSIS', 'FULL_OPINION_GENERATOR_COMPLETE_ANALYSIS', 'FULL_OPINION_GENERATOR_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_COMPLETE_ANALYSIS', 'RURAL_TIMELINE_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_INDIVIDUAL_PERIOD_DOCUMENT_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_PERIOD_DOCUMENT_ANALYSIS', 'AUDIENCE_QUESTIONS_GENERATOR_COMPLETE_ANALYSIS', 'AUDIENCE_QUESTIONS_GENERATOR_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_CONSOLIDATED_DOCUMENT_ANALYSIS', 'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_IMPACT_ANALYSIS') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period_document\` DROP COLUMN \`document\``);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period_document\` ADD \`document\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period\` CHANGE \`should_consider_period\` \`should_consider_period\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period\` CHANGE \`should_consider_last_remuneration_as_exit_date\` \`should_consider_last_remuneration_as_exit_date\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` CHANGE \`type\` \`type\` enum ('analise_rapida_cnis', 'planejamento_previdenciario_rgps', 'planejamento_aposentadoria_rpps', 'planejamento_previdenciario_professor', 'atividade_especial', 'analise_caso_judicial', 'analise_procedimento_administrativo_inss', 'gerador_perguntas_medicas', 'analise_geradora_objeção_laudo_medico_social', 'gerador_discurso', 'avaliacao_deficiencia_para_bpc', 'analise_renda_per_capita_para_bpc', 'analise_linha_tempo_rural', 'gerador_perguntas_audiencia', 'analise_qualidade_segurado') NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_de48ccd1c2a2087b6f247f298d\` ON \`analysis_tool_record\` (\`teacher_retirement_planning_id\`)`);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period_document\` ADD CONSTRAINT \`FK_f5b7efd5c1d5eb20e7055426151\` FOREIGN KEY (\`rural_timeline_cnis_contribution_period_id\`) REFERENCES \`rural_timeline_cnis_contribution_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_document\` ADD CONSTRAINT \`FK_5a7ef6d0bc6405f3e1862a59cc6\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_inss_benefit\` ADD CONSTRAINT \`FK_c3334211119f55686f6c82f4467\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_legal_proceeding\` ADD CONSTRAINT \`FK_b99de22ec91a8eb020729508a10\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period_item_document\` ADD CONSTRAINT \`FK_f390dcfeaecee81c424c6c858e0\` FOREIGN KEY (\`teacher_retirement_planning_period_item_id\`) REFERENCES \`teacher_retirement_planning_period_item\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period_item\` ADD CONSTRAINT \`FK_1d4aa88a09fcc00b5195c805f9f\` FOREIGN KEY (\`teacher_retirement_planning_period_id\`) REFERENCES \`teacher_retirement_planning_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period\` ADD CONSTRAINT \`FK_dda5b7c7d2034d4c63a53d748c6\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_remuneration\` ADD CONSTRAINT \`FK_d50a70e85425e4136767cf47bb4\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` ADD CONSTRAINT \`FK_de48ccd1c2a2087b6f247f298d0\` FOREIGN KEY (\`teacher_retirement_planning_id\`) REFERENCES \`teacher_retirement_planning\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP FOREIGN KEY \`FK_de48ccd1c2a2087b6f247f298d0\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_remuneration\` DROP FOREIGN KEY \`FK_d50a70e85425e4136767cf47bb4\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period\` DROP FOREIGN KEY \`FK_dda5b7c7d2034d4c63a53d748c6\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period_item\` DROP FOREIGN KEY \`FK_1d4aa88a09fcc00b5195c805f9f\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_period_item_document\` DROP FOREIGN KEY \`FK_f390dcfeaecee81c424c6c858e0\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_legal_proceeding\` DROP FOREIGN KEY \`FK_b99de22ec91a8eb020729508a10\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_inss_benefit\` DROP FOREIGN KEY \`FK_c3334211119f55686f6c82f4467\``);
        await queryRunner.query(`ALTER TABLE \`teacher_retirement_planning_document\` DROP FOREIGN KEY \`FK_5a7ef6d0bc6405f3e1862a59cc6\``);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period_document\` DROP FOREIGN KEY \`FK_f5b7efd5c1d5eb20e7055426151\``);
        await queryRunner.query(`DROP INDEX \`REL_de48ccd1c2a2087b6f247f298d\` ON \`analysis_tool_record\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` CHANGE \`type\` \`type\` enum ('analise_rapida_cnis', 'planejamento_previdenciario_rgps', 'planejamento_aposentadoria_rpps', 'atividade_especial', 'analise_caso_judicial', 'analise_procedimento_administrativo_inss', 'gerador_perguntas_medicas', 'analise_geradora_objeção_laudo_medico_social', 'gerador_discurso', 'avaliacao_deficiencia_para_bpc', 'analise_renda_per_capita_para_bpc', 'analise_linha_tempo_rural', 'gerador_perguntas_audiencia', 'analise_qualidade_segurado') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period\` CHANGE \`should_consider_last_remuneration_as_exit_date\` \`should_consider_last_remuneration_as_exit_date\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period\` CHANGE \`should_consider_period\` \`should_consider_period\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period_document\` DROP COLUMN \`document\``);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period_document\` ADD \`document\` varchar(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_plan_paid_resource\` CHANGE \`resource\` \`resource\` enum ('LEGAL_PLEADING_COMPLETE_ANALYSIS', 'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS', 'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS', 'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS', 'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS', 'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS', 'LEGAL_PROCEEDING_MONITORING', 'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS', 'ELOY_CHAT_LEGISLATION_QUESTIONS', 'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH', 'ELOY_CHAT_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS', 'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS', 'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS', 'SPECIAL_ACTIVITY_COMPLETE_ANALYSIS', 'SPECIAL_ACTIVITY_SIMPLIFIED_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS', 'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS', 'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS', 'MEDICAL_QUESTION_GENERATOR_SIMPLIFIED_ANALYSIS', 'MEDICAL_QUESTION_GENERATOR_COMPLETE_ANALYSIS', 'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_COMPLETE_ANALYSIS', 'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_SIMPLIFIED_ANALYSIS', 'SPEECH_GENERATOR_COMPLETE_ANALYSIS', 'SPEECH_GENERATOR_SIMPLIFIED_ANALYSIS', 'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS', 'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS', 'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS', 'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS', 'INSURANCE_QUALITY_ANALYSIS_COMPLETE_ANALYSIS', 'INSURANCE_QUALITY_ANALYSIS_SIMPLIFIED_ANALYSIS', 'INITIAL_PETITION_GENERATOR_COMPLETE_ANALYSIS', 'INITIAL_PETITION_GENERATOR_SIMPLIFIED_ANALYSIS', 'ADMINISTRATIVE_REQUEST_GENERATOR_COMPLETE_ANALYSIS', 'ADMINISTRATIVE_REQUEST_GENERATOR_SIMPLIFIED_ANALYSIS', 'FULL_OPINION_GENERATOR_COMPLETE_ANALYSIS', 'FULL_OPINION_GENERATOR_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_COMPLETE_ANALYSIS', 'RURAL_TIMELINE_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_INDIVIDUAL_PERIOD_DOCUMENT_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_PERIOD_DOCUMENT_ANALYSIS', 'AUDIENCE_QUESTIONS_GENERATOR_COMPLETE_ANALYSIS', 'AUDIENCE_QUESTIONS_GENERATOR_SIMPLIFIED_ANALYSIS', 'RURAL_TIMELINE_ANALYSIS_CONSOLIDATED_DOCUMENT_ANALYSIS', 'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_IMPACT_ANALYSIS') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP INDEX \`IDX_de48ccd1c2a2087b6f247f298d\``);
        await queryRunner.query(`ALTER TABLE \`analysis_tool_record\` DROP COLUMN \`teacher_retirement_planning_id\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning_result\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning_remuneration\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning_period\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning_period_item\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning_period_item_document\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning_legal_proceeding\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning_inss_benefit\``);
        await queryRunner.query(`DROP TABLE \`teacher_retirement_planning_document\``);
        await queryRunner.query(`ALTER TABLE \`rural_timeline_cnis_contribution_period_document\` ADD CONSTRAINT \`FK_cnis_contribution_period_document_period\` FOREIGN KEY (\`rural_timeline_cnis_contribution_period_id\`) REFERENCES \`rural_timeline_cnis_contribution_period\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
