import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateRegulatoryUpdateTables1774600000000 implements MigrationInterface {
  name = 'CreateRegulatoryUpdateTables1774600000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE \`regulatory_update\` (
        \`id\` varchar(36) NOT NULL,
        \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`deleted_at\` datetime(6) NULL,
        \`title\` varchar(255) NOT NULL,
        \`summary\` text NOT NULL,
        \`implementation_status\` text NOT NULL,
        \`beneficiary_impact\` text NOT NULL,
        \`full_text\` longtext NOT NULL,
        \`source_url\` varchar(500) NULL,
        \`published_at\` date NULL,
        PRIMARY KEY (\`id\`)
      ) ENGINE=InnoDB
    `);

    await queryRunner.query(`
      CREATE TABLE \`regulatory_update_main_change\` (
        \`id\` varchar(36) NOT NULL,
        \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`deleted_at\` datetime(6) NULL,
        \`description\` text NOT NULL,
        \`order\` int NOT NULL DEFAULT 0,
        \`regulatory_update_id\` varchar(36) NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`FK_regulatory_update_main_change_regulatory_update\`
          FOREIGN KEY (\`regulatory_update_id\`) REFERENCES \`regulatory_update\` (\`id\`)
          ON DELETE CASCADE ON UPDATE NO ACTION
      ) ENGINE=InnoDB
    `);

    await queryRunner.query(`
      CREATE TABLE \`regulatory_update_email_preference\` (
        \`id\` varchar(36) NOT NULL,
        \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`deleted_at\` datetime(6) NULL,
        \`email_enabled\` tinyint NOT NULL DEFAULT 0,
        \`customer_id\` varchar(36) NOT NULL,
        UNIQUE INDEX \`IDX_regulatory_update_email_preference_customer_id\` (\`customer_id\`),
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`FK_regulatory_update_email_preference_customer\`
          FOREIGN KEY (\`customer_id\`) REFERENCES \`customer\` (\`id\`)
          ON DELETE CASCADE ON UPDATE NO ACTION
      ) ENGINE=InnoDB
    `);

    await queryRunner.query(`
      CREATE TABLE \`regulatory_update_monitored_source\` (
        \`id\` varchar(36) NOT NULL,
        \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        \`deleted_at\` datetime(6) NULL,
        \`name\` varchar(255) NOT NULL,
        \`url\` varchar(500) NOT NULL,
        \`active\` tinyint NOT NULL DEFAULT 1,
        PRIMARY KEY (\`id\`)
      ) ENGINE=InnoDB
    `);

    await queryRunner.query(
      `ALTER TABLE \`payment_plan_paid_resource\` MODIFY COLUMN \`resource\` enum(
        'LEGAL_PLEADING_COMPLETE_ANALYSIS',
        'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS',
        'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS',
        'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS',
        'TEACHER_RETIREMENT_PLANNING_COMPLETE_ANALYSIS',
        'TEACHER_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS',
        'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS',
        'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'LEGAL_PROCEEDING_MONITORING',
        'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS',
        'ELOY_CHAT_LEGISLATION_QUESTIONS',
        'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH',
        'ELOY_CHAT_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS',
        'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS',
        'SPECIAL_ACTIVITY_COMPLETE_ANALYSIS',
        'SPECIAL_ACTIVITY_SIMPLIFIED_ANALYSIS',
        'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS',
        'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS',
        'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'MEDICAL_QUESTION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'MEDICAL_QUESTION_GENERATOR_COMPLETE_ANALYSIS',
        'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_COMPLETE_ANALYSIS',
        'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'SPEECH_GENERATOR_COMPLETE_ANALYSIS',
        'SPEECH_GENERATOR_SIMPLIFIED_ANALYSIS',
        'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS',
        'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS',
        'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'INSURANCE_QUALITY_ANALYSIS_COMPLETE_ANALYSIS',
        'INSURANCE_QUALITY_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'INITIAL_PETITION_GENERATOR_COMPLETE_ANALYSIS',
        'INITIAL_PETITION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'ADMINISTRATIVE_REQUEST_GENERATOR_COMPLETE_ANALYSIS',
        'ADMINISTRATIVE_REQUEST_GENERATOR_SIMPLIFIED_ANALYSIS',
        'FULL_OPINION_GENERATOR_COMPLETE_ANALYSIS',
        'FULL_OPINION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_COMPLETE_ANALYSIS',
        'RURAL_TIMELINE_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_INDIVIDUAL_PERIOD_DOCUMENT_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_PERIOD_DOCUMENT_ANALYSIS',
        'AUDIENCE_QUESTIONS_GENERATOR_COMPLETE_ANALYSIS',
        'AUDIENCE_QUESTIONS_GENERATOR_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_CONSOLIDATED_DOCUMENT_ANALYSIS',
        'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_IMPACT_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_COMPLETE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_SIMPLIFIED_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_ADMINISTRATIVE_REQUEST_DENIED_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_BENEFIT_AWARD_LETTER_ANALYSIS',
        'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_ADJUSTMENT_SIMULATION',
        'REGULATORY_UPDATES'
      ) NOT NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`payment_plan_paid_resource\` MODIFY COLUMN \`resource\` enum(
        'LEGAL_PLEADING_COMPLETE_ANALYSIS',
        'LEGAL_PLEADING_SIMPLIFIED_ANALYSIS',
        'LEGAL_PLEADING_QUICK_DOCUMENT_ANALYSIS',
        'RETIREMENT_PLANNING_RPPS_COMPLETE_ANALYSIS',
        'TEACHER_RETIREMENT_PLANNING_COMPLETE_ANALYSIS',
        'TEACHER_RETIREMENT_PLANNING_SIMPLIFIED_ANALYSIS',
        'CNIS_FAST_ANALYSIS_COMPLETE_ANALYSIS',
        'CNIS_FAST_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'LEGAL_PROCEEDING_MONITORING',
        'ELOY_CHAT_SOCIAL_SECURITY_QUESTIONS',
        'ELOY_CHAT_LEGISLATION_QUESTIONS',
        'ELOY_CHAT_WINNING_LEGAL_THESIS_RESEARCH',
        'ELOY_CHAT_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_CNIS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_COMPARE_CNIS_CTPS',
        'RETIREMENT_PLANNING_RGPS_SPECIAL_PERIOD_PPP_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_NO_END_DATE_DOCUMENTS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_RURAL_TIME_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_MILITARY_SERVICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_PUBLIC_SERVICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_CTPS_OUTSIDE_CNIS_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_STUDENT_APPRENTICE_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_WORK_ABROAD_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_INFORMAL_WORK_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_LABOR_COURT_DECISION_ANALYSIS',
        'RETIREMENT_PLANNING_RGPS_FINAL_RULES_ANALYSIS',
        'SPECIAL_ACTIVITY_COMPLETE_ANALYSIS',
        'SPECIAL_ACTIVITY_SIMPLIFIED_ANALYSIS',
        'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_COMPLETE_ANALYSIS',
        'ADMINISTRATIVE_PROCEDURE_INSS_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'JUDICIAL_CASE_ANALYSIS_COMPLETE_ANALYSIS',
        'JUDICIAL_CASE_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'MEDICAL_QUESTION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'MEDICAL_QUESTION_GENERATOR_COMPLETE_ANALYSIS',
        'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_COMPLETE_ANALYSIS',
        'MEDICAL_AND_SOCIAL_REPORT_OBJECTION_GENERATOR_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'SPEECH_GENERATOR_COMPLETE_ANALYSIS',
        'SPEECH_GENERATOR_SIMPLIFIED_ANALYSIS',
        'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS',
        'DISABILITY_ASSESSMENT_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_COMPLETE_ANALYSIS',
        'PER_CAPITA_INCOME_FOR_BPC_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'INSURANCE_QUALITY_ANALYSIS_COMPLETE_ANALYSIS',
        'INSURANCE_QUALITY_ANALYSIS_SIMPLIFIED_ANALYSIS',
        'INITIAL_PETITION_GENERATOR_COMPLETE_ANALYSIS',
        'INITIAL_PETITION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'ADMINISTRATIVE_REQUEST_GENERATOR_COMPLETE_ANALYSIS',
        'ADMINISTRATIVE_REQUEST_GENERATOR_SIMPLIFIED_ANALYSIS',
        'FULL_OPINION_GENERATOR_COMPLETE_ANALYSIS',
        'FULL_OPINION_GENERATOR_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_COMPLETE_ANALYSIS',
        'RURAL_TIMELINE_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_INDIVIDUAL_PERIOD_DOCUMENT_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_PERIOD_DOCUMENT_ANALYSIS',
        'AUDIENCE_QUESTIONS_GENERATOR_COMPLETE_ANALYSIS',
        'AUDIENCE_QUESTIONS_GENERATOR_SIMPLIFIED_ANALYSIS',
        'RURAL_TIMELINE_ANALYSIS_CONSOLIDATED_DOCUMENT_ANALYSIS',
        'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_IMPACT_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_COMPLETE_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_SIMPLIFIED_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_ADMINISTRATIVE_REQUEST_DENIED_ANALYSIS',
        'GENERAL_URBAN_RETIREMENT_BENEFIT_AWARD_LETTER_ANALYSIS',
        'RURAL_TIMELINE_CNIS_CONTRIBUTION_PERIOD_ADJUSTMENT_SIMULATION'
      ) NOT NULL`,
    );

    await queryRunner.query(`DROP TABLE \`regulatory_update_monitored_source\``);
    await queryRunner.query(`ALTER TABLE \`regulatory_update_email_preference\` DROP FOREIGN KEY \`FK_regulatory_update_email_preference_customer\``);
    await queryRunner.query(`DROP TABLE \`regulatory_update_email_preference\``);
    await queryRunner.query(`ALTER TABLE \`regulatory_update_main_change\` DROP FOREIGN KEY \`FK_regulatory_update_main_change_regulatory_update\``);
    await queryRunner.query(`DROP TABLE \`regulatory_update_main_change\``);
    await queryRunner.query(`DROP TABLE \`regulatory_update\``);
  }
}
