export enum TeacherRetirementPlanningRejectionDocumentTypeEnum {
  CNIS = 'CNIS',
  DENIED_ADMINISTRATIVE_PROCEDURE = 'DENIED_ADMINISTRATIVE_PROCEDURE',
  ORIGINAL_PROCESS_DOCUMENTATION = 'ORIGINAL_PROCESS_DOCUMENTATION',
  OTHER_DOCUMENTS = 'OTHER_DOCUMENTS',
}
