export enum DisabilityRetirementPlanningGrantDisabilityPeriodDocumentTypeEnum {
  MEDICAL_REPORT = 'MEDICAL_REPORT',
  COMPLEMENTARY_EXAMS = 'COMPLEMENTARY_EXAMS',
  PREVIOUS_BENEFITS = 'PREVIOUS_BENEFITS',
  VOCATIONAL_REHABILITATION = 'VOCATIONAL_REHABILITATION',
}
