export enum TemporaryDisabilityBenefitsTerminatedConditionEnum {
  CONTINUA_INCAPACITADO = 'CONTINUA_INCAPACITADO',
  HOUVE_AGRAVAMENTO = 'HOUVE_AGRAVAMENTO',
  RECUPERACAO_PARCIAL_SEM_RETORNO = 'RECUPERACAO_PARCIAL_SEM_RETORNO',
  RECUPERACAO_PARCIAL_COM_RESTRICOES = 'RECUPERACAO_PARCIAL_COM_RESTRICOES',
  INCAPACIDADE_ATIVIDADE_HABITUAL = 'INCAPACIDADE_ATIVIDADE_HABITUAL',
  OUTRO = 'OUTRO',
}
