export enum TemporaryIncapacityBenefitTerminationDocumentTypeEnum {
  CNIS = 'CNIS',
  ADMINISTRATIVE_PROCEDURE = 'ADMINISTRATIVE_PROCEDURE',
  SUSPENSION_OR_TERMINATION_PROCEDURE = 'SUSPENSION_OR_TERMINATION_PROCEDURE',
  MEDICAL_OR_SOCIAL_REPORTS = 'MEDICAL_OR_SOCIAL_REPORTS',
}
