export enum DeathBenefitRejectionDocumentTypeEnum {
  ADMINISTRATIVE_PROCEDURE_DENIED = 'ADMINISTRATIVE_PROCEDURE_DENIED',
  CNIS = 'CNIS',
  DEATH_CERTIFICATE = 'DEATH_CERTIFICATE',
  EMPLOYMENT_BOND_DOCUMENTS = 'EMPLOYMENT_BOND_DOCUMENTS',
  RURAL_DOCUMENTS = 'RURAL_DOCUMENTS',
  MEDICAL_DOCUMENTS = 'MEDICAL_DOCUMENTS',
  INVOLUNTARY_UNEMPLOYMENT_EVIDENCE = 'INVOLUNTARY_UNEMPLOYMENT_EVIDENCE',
}
