export enum GeneralUrbanRetirementAnalysisDocumentTypeEnum {
  ADMINISTRATIVE_REQUEST_DENIED = 'ADMINISTRATIVE_REQUEST_DENIED',
  BENEFIT_AWARD_LETTER = 'BENEFIT_AWARD_LETTER',
  CERTIFICATE_CONTRIBUTION_PERIOD = 'CERTIFICATE_CONTRIBUTION_PERIOD',
}
