name: CI/CD

on:
  push:
    branches: ['qa']
  workflow_dispatch:

env:
  WORKING_DIRECTORY: /workspace/container/docker/qa/agiliza-previ/agiliza-previ-back

jobs:

  build:
    runs-on: quality-assurance
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐳 Build Docker Image
        run: |
          docker build --memory="2g" --cpus="1.5" --no-cache -t ${{ vars.REGISTRY_URL }} .

  deploy:
    needs: build
    runs-on: quality-assurance
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏷️ Extract App Version
        run: echo "APP_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: ⚙️ SSH - Update Container Environment Variables
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          echo -e '${{ vars.QA_ENVS }}' > ${{ env.WORKING_DIRECTORY }}/.container.env

      - name: 🛑 SSH - Stop Old Docker Container
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          bash ${{ env.WORKING_DIRECTORY }}/remove.container.sh || true

      - name: 🚀 SSH - Start New Docker Container
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          bash ${{ env.WORKING_DIRECTORY }}/start.container.sh
