name: CI/CD

on:
  push:
    branches: ['qa']
  workflow_dispatch:

env:
  WORKING_DIRECTORY: /workspace/container/docker/qa/agiliza-previ/agiliza-previ-back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏷️ Extract App Version
        id: extract_version
        run: echo "APP_VERSION=latest" >> $GITHUB_ENV

      - name: ⚙️ Configure Docker for Insecure Registry
        run: |
          REGISTRY_HOST=$(echo "${{ vars.REGISTRY_URL }}" | cut -d/ -f1)
          echo "{ \"insecure-registries\": [\"$REGISTRY_HOST\"] }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: 🔐 Docker Login to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $(echo "${{ vars.REGISTRY_URL }}" | cut -d/ -f1) -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: 🐳 Build and Push Docker Image
        run: |
          docker build --no-cache -t ${{ vars.REGISTRY_URL }}:${{ env.APP_VERSION }} .
          docker push ${{ vars.REGISTRY_URL }}:${{ env.APP_VERSION }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏷️ Extract App Version
        run: echo "APP_VERSION=latest" >> $GITHUB_ENV

      - name: 📥 SSH - Pull and Tag Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_SSH_HOST }}
          username: ${{ secrets.QA_SSH_USER }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $(echo "${{ vars.REGISTRY_URL }}" | cut -d/ -f1) -u ${{ secrets.REGISTRY_USER }} --password-stdin
            docker pull ${{ vars.REGISTRY_URL }}:${{ env.APP_VERSION }}
            docker tag ${{ vars.REGISTRY_URL }}:${{ env.APP_VERSION }} ${{ vars.REGISTRY_URL }}:latest

      - name: 🛑 SSH - Stop Old Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_SSH_HOST }}
          username: ${{ secrets.QA_SSH_USER }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.WORKING_DIRECTORY }}
            bash ${{ env.WORKING_DIRECTORY }}/remove.container.sh

      - name: ⚙️ SSH - Update Container Environment Variables
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_SSH_HOST }}
          username: ${{ secrets.QA_SSH_USER }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          script: |
            echo -e '${{ vars.QA_ENVS }}' > ${{ env.WORKING_DIRECTORY }}/.container.env

      - name: 🚀 SSH - Start New Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QA_SSH_HOST }}
          username: ${{ secrets.QA_SSH_USER }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.WORKING_DIRECTORY }}
            bash ${{ env.WORKING_DIRECTORY }}/start.container.sh
